import type { CombinedFootingAnalysis } from '../../application/combined-footing-analysis'
import type { CombinedFootingInputs } from '../../domain/projects'
import type { CombinedFootingCalculationReport } from '../../reports/combined-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: CombinedFootingAnalysis | null; inputs: CombinedFootingInputs; report: CombinedFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)
const area = (value: number | null) => value === null ? 'Sección insuficiente' : `${n(value / 100, 2)} cm²/m`

export function CombinedCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata combinada para generar la memoria completa.</p></section>
  const traceability = report.profile.traceability.filter((item) => item.appliesTo.includes('combined'))
  const governingPunching = analysis.punching.reduce((governing, item) => item.utilization > governing.utilization ? item : governing)
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA COMBINADA</span><h2>{report.project.name}</h2><p>Memoria para dos columnas alineadas · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, modelo y fuentes"><Table rows={[['Perfil técnico', report.profile.label], ['Modelo', 'Zapata combinada rectangular rígida'], ['Columnas', 'Dos interiores, alineadas y centradas transversalmente'], ['Contacto', 'Presión lineal y compresión en toda la base']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría y profundidad efectiva"><Equation name="Área de cimentación" expression="A = B × L" substitution={`${n(inputs.footingWidthM)} × ${n(inputs.footingLengthM)} m`} result={`${n(analysis.contact.areaM2)} m²`}/><Equation name="Centroide longitudinal" expression="xᶜ = L/2" substitution={`${n(inputs.footingLengthM)} / 2`} result={`${n(inputs.footingLengthM/2)} m`}/><Equation name="Profundidad efectiva" expression="d = h − c − dᵦ/2" substitution={`${n(inputs.footingThicknessM)} − ${n(inputs.concreteCoverM)} − ${n(inputs.barDiameterM)}/2`} result={`${n(analysis.structural.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Contacto de servicio"><Equation name="Peso propio" expression="Wz = B × L × h × γc" substitution={`${n(inputs.footingWidthM)} × ${n(inputs.footingLengthM)} × ${n(inputs.footingThicknessM)} × ${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.contact.footingSelfWeightKn,2)} kN`}/><Equation name="Carga vertical total" expression="P = P₁ + P₂ + Wz + Wr" substitution={`${n(inputs.serviceColumn1LoadKn,2)} + ${n(inputs.serviceColumn2LoadKn,2)} + ${n(analysis.contact.footingSelfWeightKn,2)} + ${n(analysis.contact.soilCoverWeightKn,2)}`} result={`${n(analysis.contact.gross.totalLoadKn,2)} kN`}/><Equation name="Momento respecto al centroide" expression="M = P₁(x₁−L/2) + P₂(x₂−L/2)" substitution={`${n(inputs.serviceColumn1LoadKn,1)}(${n(inputs.column1CenterFromLeftM)}−${n(inputs.footingLengthM/2)}) + ${n(inputs.serviceColumn2LoadKn,1)}(${n(inputs.column2CenterFromLeftM)}−${n(inputs.footingLengthM/2)})`} result={`${n(analysis.contact.gross.momentAboutCentroidKnM,2)} kN·m`}/><Equation name="Excentricidad" expression="e = M/P" substitution={`${n(analysis.contact.gross.momentAboutCentroidKnM,2)} / ${n(analysis.contact.gross.totalLoadKn,2)}`} result={`${n(analysis.contact.gross.eccentricityM,4)} m`}/><Equation name="Presiones extremas" expression="qizq,der = P/(BL) × (1 ∓ 6e/L)" substitution={`${n(analysis.contact.gross.averagePressureKpa,2)} × (1 ∓ 6×${n(analysis.contact.gross.eccentricityM,4)}/${n(inputs.footingLengthM)})`} result={`${n(analysis.contact.grossPressureLeftKpa,2)} / ${n(analysis.contact.grossPressureRightKpa,2)} kPa`}/><Table rows={[['Base comparada', inputs.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión máxima comparada', `${n(analysis.contact.maximumPressureForComparisonKpa,2)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa,2)} kPa`], ['Utilización', `${n(analysis.contact.utilization*100,1)}% · ${analysis.contact.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada'}`], ['Contacto mínimo bruto', `${n(analysis.contact.gross.minimumPressureKpa,2)} kPa · sin levantamiento`]]}/></MemoSection>
    <MemoSection number="05" title="Presión última y equilibrio longitudinal"><Equation name="Carga última total" expression="Pᵤ = Pᵤ₁ + Pᵤ₂" substitution={`${n(inputs.factoredColumn1LoadKn,2)} + ${n(inputs.factoredColumn2LoadKn,2)}`} result={`${n(analysis.structural.factored.totalLoadKn,2)} kN`}/><Equation name="Presiones últimas extremas" expression="qᵤ,izq,der = Pᵤ/(BL) × (1 ∓ 6eᵤ/L)" substitution={`eᵤ = ${n(analysis.structural.factored.eccentricityM,4)} m`} result={`${n(analysis.structural.factoredPressureLeftKpa,2)} / ${n(analysis.structural.factoredPressureRightKpa,2)} kPa`}/><Equation name="Reacción lineal" expression="w(x) = B × qᵤ(x)" substitution={`B = ${n(inputs.footingWidthM)} m; qᵤ lineal`} result={`w(0) = ${n(inputs.footingWidthM*analysis.structural.factoredPressureLeftKpa,2)} kN/m; w(L) = ${n(inputs.footingWidthM*analysis.structural.factoredPressureRightKpa,2)} kN/m`}/><Equation name="Cortante interno" expression="V(x) = ∫₀ˣw(s)ds − ΣPᵤ,i" substitution="Las cargas se incluyen después de cruzar cada centro de columna." result={`V(L) = ${n(analysis.longitudinal.endShearKn,6)} kN`}/><Equation name="Momento interno" expression="M(x) = ∫₀ˣw(s)(x−s)ds − ΣPᵤ,i(x−xᵢ)" substitution="Se evalúan extremos, centros de columna y raíces de V(x)." result={`M(L) = ${n(analysis.longitudinal.endMomentKnM,6)} kN·m`}/><Table rows={[['Momento positivo máximo', `${n(analysis.longitudinal.maximumPositiveMomentKnM,2)} kN·m en x=${n(analysis.longitudinal.maximumPositiveMomentXM)} m`], ['Momento negativo mínimo', `${n(analysis.longitudinal.minimumNegativeMomentKnM,2)} kN·m en x=${n(analysis.longitudinal.minimumNegativeMomentXM)} m`], ['Momento absoluto gobernante', `${n(analysis.longitudinal.governingAbsoluteMomentKnM,2)} kN·m`]]}/></MemoSection>
    <MemoSection number="06" title="Cortante unidireccional"><Table rows={analysis.longitudinal.criticalShearSections.map((section) => [`Sección ${section.label} · x=${n(section.xM)} m`, `${n(section.shearKn,2)} kN`])}/><Equation name="Demanda longitudinal gobernante" expression="Vᵤ = máx |V(xcara ± d)|" substitution={analysis.longitudinal.criticalShearSections.map((section)=>n(Math.abs(section.shearKn),2)).join('; ')} result={`${n(analysis.longitudinal.governingShearDemandKn,2)} kN`}/><Equation name="Demanda transversal por metro" expression="Vᵤ,t = qlocal × máx(a−d,0)" substitution={`${n(analysis.transverse.shearLocalPressureKpa,2)} × ${n(analysis.transverse.loadedLengthBeyondCriticalSectionM)}`} result={`${n(analysis.transverse.oneWayShearDemandKnPerM,2)} kN/m · columna ${analysis.transverse.governingShearColumn}`}/><Table rows={[['Referencia longitudinal', `${n(analysis.shearReference.longitudinal.designShearStrengthKn,2)} kN · η ${n(analysis.shearReference.longitudinal.utilization*100,1)}%`], ['Referencia transversal', `${n(analysis.shearReference.transverse.designShearStrengthKn,2)} kN/m · η ${n(analysis.shearReference.transverse.utilization*100,1)}%`]]}/></MemoSection>
    <MemoSection number="07" title="Punzonamiento por columna"><Table rows={analysis.punching.flatMap((item) => [[`Columna ${item.column} · perímetro b₀`, `${n(item.criticalPerimeterM)} m`], [`Columna ${item.column} · reacción interior`, `${n(item.soilReactionInsideKn,2)} kN`], [`Columna ${item.column} · Vᵤ`, `${n(item.shearDemandKn,2)} kN`], [`Columna ${item.column} · φVᶜ y utilización`, `${n(item.designShearStrengthKn,2)} kN · ${n(item.utilization*100,1)}%`]] as Array<[string,string]>)}/><p className="memo-muted">Gobierna la columna {governingPunching.column}. Solo se aceptan perímetros interiores completos.</p></MemoSection>
    <MemoSection number="08" title="Flexión y armado"><Equation name="Flexión transversal por metro" expression="Mᵤ,t = qlocal × a²/2" substitution={`${n(analysis.transverse.flexureLocalPressureKpa,2)} × ${n(analysis.transverse.cantileverProjectionM)}² / 2`} result={`${n(analysis.transverse.flexureDemandKnMPerM,2)} kN·m/m · columna ${analysis.transverse.governingFlexureColumn}`}/><Equation name="Acero mínimo" expression="Aₛ,min = 0.0018 × 1000 × h(mm)" substitution={`0.0018 × 1000 × ${n(inputs.footingThicknessM*1000,0)}`} result={`${n(analysis.minimumReinforcement.minimumAreaPerMeterCm2,2)} cm²/m`}/><Table rows={[['Longitudinal inferior requerido', area(analysis.reinforcement.longitudinalBottom.requiredAreaPerMeterMm2)], ['Longitudinal inferior colocado', area(analysis.reinforcement.longitudinalBottom.providedAreaPerMeterMm2)], ['Longitudinal superior requerido', area(analysis.reinforcement.longitudinalTop.requiredAreaPerMeterMm2)], ['Longitudinal superior colocado', area(analysis.reinforcement.longitudinalTop.providedAreaPerMeterMm2)], ['Transversal requerido', area(analysis.reinforcement.transverse.requiredAreaPerMeterMm2)], ['Transversal colocado', area(analysis.reinforcement.transverse.providedAreaPerMeterMm2)]]}/></MemoSection>
    <MemoSection number="09" title="Desarrollo y exclusiones"><Equation name="Longitud requerida" expression="lᵈ = fy/(1.4√f′c) × dᵦ" substitution={`${n(inputs.steelYieldStrengthMpa,2)}/(1.4√${n(inputs.concreteStrengthMpa,2)}) × ${n(inputs.barDiameterM)}`} result={`${n(analysis.development.requiredDevelopmentLengthM)} m`}/><Table rows={[['Disponible longitudinal', `${n(inputs.longitudinalDevelopmentAvailableM)} m · ${analysis.development.lengthDirection.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Disponible transversal', `${n(inputs.transverseDevelopmentAvailableM)} m · ${analysis.development.widthDirection.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Contacto parcial o levantamiento', 'Fuera de alcance; el motor bloquea el caso'], ['Columnas de borde, momentos y acciones horizontales', 'Fuera de alcance'], ['Asentamientos', 'Revisión externa del estudio geotécnico']]}/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value], index) => <div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: CombinedFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: CombinedFootingCalculationReport['profile']['traceability']; sources: CombinedFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
