import type { StrapFootingAnalysis, StrapPadAnalysis } from '../../application/strap-footing-analysis'
import type { StrapFootingInputs } from '../../domain/projects'
import type { StrapFootingCalculationReport } from '../../reports/strap-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: StrapFootingAnalysis | null; inputs: StrapFootingInputs; report: StrapFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)
const cm2 = (value: number | null) => value === null ? 'Sección insuficiente' : `${n(value/100,2)} cm²`
const cm2m = (value: number | null) => value === null ? 'Sección insuficiente' : `${n(value/100,2)} cm²/m`
const state = (value: string) => value === 'meets-guide-reference' ? 'Dentro de referencia' : value === 'section-insufficient' ? 'Sección insuficiente' : 'Requiere ajuste'

export function StrapCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata medianera para generar la secuencia completa.</p></section>
  const traceability = report.profile.traceability.filter((item) => item.appliesTo.includes('strap'))
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA MEDIANERA</span><h2>{report.project.name}</h2><p>Memoria de dos bases con viga centradora · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, modelo y fuentes"><Table rows={[["Perfil técnico", report.profile.label], ['Modelo', 'Dos bases rectangulares y viga centradora rígida'], ['Acciones', 'Cargas verticales declaradas; excentricidad en un eje'], ['Hipótesis esencial', 'El tramo libre de la viga no transmite reacción al suelo']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría, excentricidad y profundidades"><Equation name="Área de la base medianera" expression="Aₑ = Bₑ × Lₑ" substitution={`${n(inputs.exteriorFootingWidthM)} × ${n(inputs.exteriorFootingLengthM)}`} result={`${n(analysis.geometry.exteriorAreaM2)} m²`}/><Equation name="Área de la base interior" expression="Aᵢ = Bᵢ × Lᵢ" substitution={`${n(inputs.interiorFootingWidthM)} × ${n(inputs.interiorFootingLengthM)}`} result={`${n(analysis.geometry.interiorAreaM2)} m²`}/><Equation name="Excentricidad medianera" expression="e = Lₑ/2 − xₑ" substitution={`${n(inputs.exteriorFootingLengthM)}/2 − ${n(inputs.exteriorColumnCenterFromOuterEdgeM)}`} result={`${n(analysis.geometry.exteriorEccentricityM)} m`}/><Equation name="Tramo libre de viga" expression="Lᵥ = S − Lₑ/2 − Lᵢ/2" substitution={`${n(inputs.footingCenterSpacingM)} − ${n(inputs.exteriorFootingLengthM)}/2 − ${n(inputs.interiorFootingLengthM)}/2`} result={`${n(analysis.geometry.clearStrapLengthM)} m`}/><Table rows={[["d base medianera", `${n(analysis.geometry.exteriorEffectiveDepthM)} m`], ['d base interior', `${n(analysis.geometry.interiorEffectiveDepthM)} m`], ['d viga', `${n(analysis.geometry.beamEffectiveDepthM)} m`]]}/></MemoSection>
    <MemoSection number="04" title="Equilibrio de servicio y transferencia"><Equation name="Momento excéntrico de servicio" expression="Mₛ = Pₛ,ₑ × e" substitution={`${n(inputs.serviceExteriorLoadKn,1)} × ${n(analysis.geometry.exteriorEccentricityM)}`} result={`${n(analysis.service.eccentricMomentKnM,2)} kN·m`}/><Equation name="Cortante transferido por la viga" expression="Vₛ = Mₛ / S" substitution={`${n(analysis.service.eccentricMomentKnM,2)} / ${n(inputs.footingCenterSpacingM)}`} result={`${n(analysis.service.strapShearKn,2)} kN`}/><Equation name="Reacción estructural exterior" expression="Rₛ,ₑ = Pₛ,ₑ + Vₛ" substitution={`${n(inputs.serviceExteriorLoadKn,1)} + ${n(analysis.service.strapShearKn,2)}`} result={`${n(analysis.service.exteriorStructuralReactionKn,2)} kN`}/><Equation name="Reacción estructural interior" expression="Rₛ,ᵢ = Pₛ,ᵢ − Vₛ" substitution={`${n(inputs.serviceInteriorLoadKn,1)} − ${n(analysis.service.strapShearKn,2)}`} result={`${n(analysis.service.interiorStructuralReactionKn,2)} kN`}/><Table rows={[["Comprobación vertical", `${n(analysis.service.exteriorStructuralReactionKn+analysis.service.interiorStructuralReactionKn,2)} = ${n(inputs.serviceExteriorLoadKn+inputs.serviceInteriorLoadKn,2)} kN`], ['Condición', 'Ambas reacciones son positivas']]}/></MemoSection>
    <MemoSection number="05" title="Contacto de servicio bajo cada base"><Equation name="Peso propio base medianera" expression="Wₑ = Aₑhₑγc" substitution={`${n(analysis.geometry.exteriorAreaM2)} × ${n(inputs.exteriorFootingThicknessM)} × ${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.service.exteriorPadSelfWeightKn,2)} kN`}/><Equation name="Peso propio base interior" expression="Wᵢ = Aᵢhᵢγc" substitution={`${n(analysis.geometry.interiorAreaM2)} × ${n(inputs.interiorFootingThicknessM)} × ${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.service.interiorPadSelfWeightKn,2)} kN`}/><Equation name="Peso del tramo libre de viga" expression="Wᵥ = Lᵥbᵥhᵥγc" substitution={`${n(analysis.geometry.clearStrapLengthM)} × ${n(inputs.strapBeamWidthM)} × ${n(inputs.strapBeamDepthM)} × ${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.service.clearStrapSelfWeightKn,2)} kN`}/><Equation name="Presiones brutas" expression="qg = (Rₛ + Wz + Wr + Wᵥ/2) / A" substitution={`Rₑ,g = ${n(analysis.service.exteriorGrossReactionKn,2)}; Rᵢ,g = ${n(analysis.service.interiorGrossReactionKn,2)} kN`} result={`${n(analysis.service.exteriorGrossPressureKpa,2)} / ${n(analysis.service.interiorGrossPressureKpa,2)} kPa`}/><Equation name="Presiones netas" expression="qn = qg − qrem" substitution={`qrem = ${n(inputs.removedOverburdenKpa,2)} kPa`} result={`${n(analysis.service.exteriorNetPressureKpa,2)} / ${n(analysis.service.interiorNetPressureKpa,2)} kPa`}/><Table rows={[["Base comparada", inputs.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión gobernante', `${n(analysis.service.governingPressureKpa,2)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa,2)} kPa`], ['Utilización', `${n(analysis.service.utilization*100,1)}% · ${analysis.service.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada'}`]]}/></MemoSection>
    <MemoSection number="06" title="Equilibrio último y presiones estructurales"><Equation name="Momento último" expression="Mᵤ = Pᵤ,ₑ × e" substitution={`${n(inputs.factoredExteriorLoadKn,1)} × ${n(analysis.geometry.exteriorEccentricityM)}`} result={`${n(analysis.factored.eccentricMomentKnM,2)} kN·m`}/><Equation name="Cortante último transferido" expression="Vᵥ,ᵤ = Mᵤ / S" substitution={`${n(analysis.factored.eccentricMomentKnM,2)} / ${n(inputs.footingCenterSpacingM)}`} result={`${n(analysis.factored.strapShearKn,2)} kN`}/><Equation name="Reacciones últimas" expression="Rᵤ,ₑ = Pᵤ,ₑ + Vᵥ,ᵤ; Rᵤ,ᵢ = Pᵤ,ᵢ − Vᵥ,ᵤ" substitution={`${n(inputs.factoredExteriorLoadKn,1)} + ${n(analysis.factored.strapShearKn,2)}; ${n(inputs.factoredInteriorLoadKn,1)} − ${n(analysis.factored.strapShearKn,2)}`} result={`${n(analysis.factored.exteriorReactionKn,2)} / ${n(analysis.factored.interiorReactionKn,2)} kN`}/><Equation name="Presiones últimas uniformes" expression="qᵤ = Rᵤ/A" substitution={`${n(analysis.factored.exteriorReactionKn,2)}/${n(analysis.geometry.exteriorAreaM2)}; ${n(analysis.factored.interiorReactionKn,2)}/${n(analysis.geometry.interiorAreaM2)}`} result={`${n(analysis.factored.exteriorPressureKpa,2)} / ${n(analysis.factored.interiorPressureKpa,2)} kPa`}/></MemoSection>
    <MemoSection number="07" title="Cortante unidireccional de las bases"><PadShear name="Base medianera" pad={analysis.pads.exterior}/><PadShear name="Base interior" pad={analysis.pads.interior}/><p className="memo-muted">Para cada dirección se usa Vᵤ = qᵤ × ancho de sección × máx(a−d,0), y se compara con φVᶜ = 0.75 × 0.17√f′c × b × d.</p></MemoSection>
    <MemoSection number="08" title="Flexión y armado de las bases"><PadSteel name="Base medianera" pad={analysis.pads.exterior}/><PadSteel name="Base interior" pad={analysis.pads.interior}/><Equation name="Acero mínimo" expression="Aₛ,min = 0.0018 × 1000 × h(mm)" substitution={`hₑ=${n(inputs.exteriorFootingThicknessM*1000,0)} mm; hᵢ=${n(inputs.interiorFootingThicknessM*1000,0)} mm`} result={`${n(analysis.pads.exterior.minimumReinforcement.minimumAreaPerMeterCm2,2)} / ${n(analysis.pads.interior.minimumReinforcement.minimumAreaPerMeterCm2,2)} cm²/m`}/></MemoSection>
    <MemoSection number="09" title="Viga, desarrollo y punzonamiento"><Equation name="Demanda de la viga" expression="Mᵤ = Pᵤ,ₑe; Vᵤ = Mᵤ/S" substitution={`${n(inputs.factoredExteriorLoadKn,1)} × ${n(analysis.geometry.exteriorEccentricityM)}; ${n(analysis.beam.momentDemandKnM,2)}/${n(inputs.footingCenterSpacingM)}`} result={`${n(analysis.beam.momentDemandKnM,2)} kN·m; ${n(analysis.beam.shearDemandKn,2)} kN`}/><Table rows={[["Cortante de referencia", `${n(analysis.beam.shearReference.designShearStrengthKn,2)} kN · η ${n(analysis.beam.shearReference.utilization*100,1)}%`], ['Acero requerido en viga', cm2(analysis.beam.requiredLongitudinalAreaMm2)], ['Acero colocado en viga', `${cm2(analysis.beam.providedLongitudinalAreaMm2)} · ${state(analysis.beam.reinforcementStatus)}`], ['Desarrollo requerido', `${n(analysis.development.requiredDevelopmentLengthM)} m`], ['Disponible en bases', `${n(inputs.padDevelopmentAvailableM)} m · ${state(analysis.development.widthDirection.status)}`], ['Anclaje disponible de viga', `${n(inputs.beamDevelopmentAvailableM)} m · ${state(analysis.development.lengthDirection.status)}`], ['Punzonamiento', `NO EVALUADO · ${analysis.punching.reason}`]]}/></MemoSection>
    <MemoSection number="10" title="Conclusión, límites y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function PadShear({ name, pad }: { name: string; pad: StrapPadAnalysis }) { return <Table rows={[[`${name} · qᵤ`, `${n(pad.factoredPressureKpa,2)} kPa`], [`${name} · longitudinal`, `a=${n(pad.longitudinal.projectionM)} m; Vᵤ=${n(pad.longitudinal.shearDemandKn,2)} kN; φVᶜ=${n(pad.longitudinal.shearReference.designShearStrengthKn,2)} kN; η=${n(pad.longitudinal.shearReference.utilization*100,1)}%`], [`${name} · transversal`, `a=${n(pad.transverse.projectionM)} m; Vᵤ=${n(pad.transverse.shearDemandKn,2)} kN; φVᶜ=${n(pad.transverse.shearReference.designShearStrengthKn,2)} kN; η=${n(pad.transverse.shearReference.utilization*100,1)}%`]]}/> }
function PadSteel({ name, pad }: { name: string; pad: StrapPadAnalysis }) { return <Table rows={[[`${name} · Mᵤ longitudinal`, `${n(pad.longitudinal.flexureDemandKnM,2)} kN·m`], [`${name} · Aₛ longitudinal requerido / colocado`, `${cm2m(pad.longitudinal.reinforcement.governingAreaPerMeterMm2)} / ${cm2m(pad.longitudinal.reinforcement.providedAreaPerMeterMm2)} · ${state(pad.longitudinal.reinforcement.status)}`], [`${name} · Mᵤ transversal`, `${n(pad.transverse.flexureDemandKnM,2)} kN·m`], [`${name} · Aₛ transversal requerido / colocado`, `${cm2m(pad.transverse.reinforcement.governingAreaPerMeterMm2)} / ${cm2m(pad.transverse.reinforcement.providedAreaPerMeterMm2)} · ${state(pad.transverse.reinforcement.status)}`]]}/> }
function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value], index) => <div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: StrapFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: StrapFootingCalculationReport['profile']['traceability']; sources: StrapFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
