import type { StrapFootingAnalysis } from '../../application/strap-footing-analysis'
import { StrapFootingPlanSheet } from '../../components/StrapFootingTechnicalSheets'
import type { ProjectDocument, StrapFootingInputs } from '../../domain/projects'
import { strapCaseFieldDefinitions, strapCaseFieldGroups, type StrapCaseField, type StrapInputText } from './strap-case-fields'

type Props = {
  project: ProjectDocument; text: StrapInputText; openGroup: string; formatIssue: string | null
  analysis: StrapFootingAnalysis | null; onOpenGroup: (id: string) => void; onNameChange: (name: string) => void
  onFieldChange: (key: StrapCaseField, value: string) => void
  onBasisChange: (basis: StrapFootingInputs['bearingCapacityBasis']) => void; onAnalyze: () => void
}

export function StrapCaseDefinition({ project, text, openGroup, formatIssue, analysis, onOpenGroup, onNameChange, onFieldChange, onBasisChange, onAnalyze }: Props) {
  return <section className="new-definition"><aside><div className="side-head"><span>01 · ZAPATA MEDIANERA</span><h1>Viga centradora</h1><p>Dos bases independientes enlazadas para equilibrar la excentricidad.</p></div>{formatIssue && <p className="format-issue">{formatIssue}</p>}{strapCaseFieldGroups.map((group) => { const opened = openGroup === group.id; const completed = group.keys.filter((key) => Number(text[key].replace(',', '.')) > 0).length; return <section className="fold" key={group.id}><button className="fold-trigger" onClick={() => onOpenGroup(opened ? '' : group.id)} aria-expanded={opened}><span><b>{group.label}</b><small>{opened ? group.description : group.keys.length ? `${completed}/${group.keys.length} valores declarados` : 'Identificación y límites'}</small></span><i>{opened ? '−' : '+'}</i></button>{opened && <div className="fold-body">{group.id === 'project' && <><label className="project-field">Nombre del proyecto<input value={project.name} onChange={(event) => onNameChange(event.target.value)}/></label><p className="scope-note">La viga no apoya en el suelo. Punzonamiento en los encuentros, estribos y nudos requieren revisión especializada.</p></>}{group.keys.map((key) => { const field = strapCaseFieldDefinitions.find((item) => item.key === key)!; return <label className="new-input" key={key}><span>{field.label}<small>{field.help}</small></span><div><input value={text[key]} inputMode="decimal" onChange={(event) => onFieldChange(key, event.target.value)}/><em>{field.unit}</em></div></label> })}{group.id === 'soil' && <label className="basis-input"><span>Base de la capacidad declarada</span><select value={project.strapInputSnapshot.bearingCapacityBasis} onChange={(event) => onBasisChange(event.target.value as StrapFootingInputs['bearingCapacityBasis'])}><option value="gross">Bruta</option><option value="net">Neta</option></select><small>Debe coincidir con el estudio geotécnico.</small></label>}</div>}</section> })}<button className="side-analyze" onClick={onAnalyze}>Analizar zapata medianera</button></aside><section className="drawing-intro"><div><span>REPRESENTACIÓN PRELIMINAR</span><h1>Planta del sistema</h1><p>El lindero, la excentricidad y el tramo sin apoyo quedan visibles.</p></div><StrapFootingPlanSheet inputs={project.strapInputSnapshot} analysis={analysis}/></section></section>
}
