import type { StripFootingAnalysis } from '../../application/strip-footing-analysis'
import type { StripFootingInputs } from '../../domain/projects'
import type { StripFootingCalculationReport } from '../../reports/strip-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: StripFootingAnalysis | null; inputs: StripFootingInputs; report: StripFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)

export function StripCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata corrida para generar la memoria de la franja de un metro.</p></section>
  const stripTraceability = report.profile.traceability.filter((item) => item.appliesTo.includes('strip'))
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA CORRIDA</span><h2>{report.project.name}</h2><p>Memoria por franja longitudinal de 1.00 m · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, modelo y fuentes"><Table rows={[['Perfil técnico', report.profile.label], ['Modelo', 'Zapata corrida bajo muro y carga lineal centrados'], ['Franja de cálculo', '1.00 m de longitud'], ['Reacción del suelo', 'Uniforme']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría transversal"><Equation name="Voladizo a cada lado" expression="a = (B − tᵥ) / 2" substitution={`(${n(inputs.footingWidthM)} − ${n(inputs.wallThicknessM)}) / 2 m`} result={`${n(analysis.structural.cantileverProjectionM)} m`}/><Equation name="Profundidad efectiva" expression="d = h − c − dᵦ/2" substitution={`${n(inputs.footingThicknessM)} − ${n(inputs.concreteCoverM)} − ${n(inputs.barDiameterM)}/2 m`} result={`${n(analysis.structural.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Contacto de servicio por metro"><Equation name="Peso propio" expression="Wz = B × h × γc × 1 m" substitution={`${n(inputs.footingWidthM)} × ${n(inputs.footingThicknessM)} × ${n(inputs.concreteUnitWeightKnM3)} kN/m³`} result={`${n(analysis.contact.footingSelfWeightKnM, 2)} kN/m`}/><Equation name="Carga total de servicio" expression="Ptotal = Pserv + Wz + Wrelleno" substitution={`${n(inputs.serviceLineLoadKnM, 2)} + ${n(analysis.contact.footingSelfWeightKnM, 2)} + ${n(analysis.contact.soilCoverWeightKnM, 2)} kN/m`} result={`${n(analysis.contact.totalServiceLineLoadKnM, 2)} kN/m`}/><Equation name="Presión bruta" expression="q = Ptotal / B" substitution={`${n(analysis.contact.totalServiceLineLoadKnM, 2)} / ${n(inputs.footingWidthM)} kN/m²`} result={`${n(analysis.contact.grossContactPressureKpa, 2)} kPa`}/><Table rows={[['Presión comparada', `${n(analysis.contact.pressureForComparisonKpa, 2)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa, 2)} kPa`], ['Utilización', `${n(analysis.contact.utilization * 100, 1)}% · ${analysis.contact.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada'}`]]}/></MemoSection>
    <MemoSection number="05" title="Presión última y cortante"><Equation name="Presión última" expression="qᵤ = Pᵤ / B" substitution={`${n(inputs.factoredLineLoadKnM, 2)} / ${n(inputs.footingWidthM)} kN/m²`} result={`${n(analysis.structural.factoredContactPressureKpa, 2)} kPa`}/><Equation name="Longitud cargada exterior" expression="x = máx(a − d, 0)" substitution={`máx(${n(analysis.structural.cantileverProjectionM)} − ${n(analysis.structural.effectiveDepthM)}, 0) m`} result={`${n(analysis.structural.loadedLengthBeyondCriticalSectionM)} m`}/><Equation name="Demanda de cortante por lado" expression="Vᵤ = qᵤ × x × 1 m" substitution={`${n(analysis.structural.factoredContactPressureKpa, 2)} × ${n(analysis.structural.loadedLengthBeyondCriticalSectionM)} × 1`} result={`${n(analysis.structural.oneWayShearDemandKnPerM, 2)} kN/m`}/><Equation name="Resistencia de referencia" expression="φVᶜ = 0.75 × 0.17√f′c × 1000 × d" substitution={`0.75 × ${n(analysis.shearConcreteStressMpa, 3)} × 1000 × ${n(analysis.structural.effectiveDepthM)}`} result={`${n(analysis.shearReference.designShearStrengthKn, 2)} kN/m · η ${n(analysis.shearReference.utilization * 100, 1)}%`}/></MemoSection>
    <MemoSection number="06" title="Flexión transversal"><Equation name="Momento en cara del muro" expression="Mᵤ = qᵤ × 1 m × a² / 2" substitution={`${n(analysis.structural.factoredContactPressureKpa, 2)} × 1 × ${n(analysis.structural.cantileverProjectionM)}² / 2`} result={`${n(analysis.structural.flexureDemandKnMPerM, 2)} kN·m/m`}/><p className="memo-muted">No se genera momento longitudinal: el modelo supone carga lineal uniforme y continuidad sin extremos ni discontinuidades.</p></MemoSection>
    <MemoSection number="07" title="Armado por metro"><Equation name="Área de barra" expression="Aᵦ = πdᵦ²/4" substitution={`Ø ${n(inputs.barDiameterM * 1000, 0)} mm`} result={`${n(analysis.reinforcement.barAreaMm2, 1)} mm²`}/><Equation name="Acero mínimo" expression="Aₛ,min = 0.0018 × 1000 × h(mm)" substitution={`0.0018 × 1000 × ${n(inputs.footingThicknessM * 1000, 0)}`} result={`${n(analysis.minimumReinforcement.minimumAreaPerMeterCm2, 2)} cm²/m`}/><Table rows={[['Requerido por flexión transversal', analysis.requiredTransverseReinforcement.requiredAreaPerMeterCm2 === null ? 'Sección insuficiente' : `${n(analysis.requiredTransverseReinforcement.requiredAreaPerMeterCm2, 2)} cm²/m`], ['Gobernante transversal', analysis.reinforcement.transverseGoverningAreaPerMeterMm2 === null ? 'Sección insuficiente' : `${n(analysis.reinforcement.transverseGoverningAreaPerMeterMm2 / 100, 2)} cm²/m`], ['Colocado transversal', `${n(analysis.reinforcement.transverseProvidedAreaPerMeterMm2 / 100, 2)} cm²/m`], ['Colocado longitudinal', `${n(analysis.reinforcement.longitudinalProvidedAreaPerMeterMm2 / 100, 2)} cm²/m`], ['Criterio longitudinal', 'Mínimo de distribución de referencia']]}/></MemoSection>
    <MemoSection number="08" title="Desarrollo transversal"><Equation name="Longitud requerida" expression="lᵈ = fy/(1.4√f′c) × dᵦ" substitution={`${n(inputs.steelYieldStrengthMpa, 2)}/(1.4√${n(inputs.concreteStrengthMpa, 2)}) × ${n(inputs.barDiameterM)}`} result={`${n(analysis.development.requiredDevelopmentLengthM)} m`}/><Table rows={[['Longitud disponible declarada', `${n(inputs.developmentAvailableLengthM)} m`], ['Estado', analysis.development.widthDirection.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste']]}/></MemoSection>
    <MemoSection number="09" title="Revisiones no aplicables"><Table rows={[['Punzonamiento de columna', 'No aplica al modelo continuo bajo muro'], ['Extremos y esquinas', 'Fuera del alcance actual'], ['Excentricidad y momentos del muro', 'Fuera del alcance actual'], ['Asentamientos', 'Dependen del estudio geotécnico']]}/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={stripTraceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: StripFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: StripFootingCalculationReport['profile']['traceability']; sources: StripFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
