import type { FootingAnalysis } from '../../application/footing-analysis'
import type { FootingInputs } from '../../domain/projects'
import type { FootingCalculationReport } from '../../reports/footing-calculation-report'
import type { ResultCard } from '../results/result-cards'
import { resultCardLabel } from '../results/result-cards'

type Props = {
  analysis: FootingAnalysis | null
  inputs: FootingInputs
  report: FootingCalculationReport
  cards: ResultCard[]
}

const n = (value: number, decimals = 3) => value.toFixed(decimals)

export function CalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza el caso para generar una memoria trazable con las entradas, procedimientos y resultados disponibles.</p></section>

  const { contact, oneWay, flexure, punchingDemand, reinforcementLayout, minimumReinforcement, requiredReinforcement, reinforcement, oneWayGuide, punchingGuide, development } = analysis
  return <article className="calculation-memo">
    <header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATAS</span><h2>{report.project.name}</h2><p>Memoria de revisión del caso · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, alcance y procedencia"><Table rows={[['Perfil técnico', report.profile.label], ['Estado de liberación', report.profile.releaseStatus], ['Alcance', 'Zapata rectangular, columna centrada y carga axial centrada.'], ['Exclusiones', 'Excentricidad, presión no uniforme, asentamientos, zapatas combinadas, corridas y losas.']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría base y profundidad efectiva"><Equation name="Área de contacto" expression="A = B × L" substitution={`${n(inputs.footingWidthM)} m × ${n(inputs.footingLengthM)} m`} result={`${n(oneWay.footingAreaM2)} m²`}/><Equation name="Profundidad efectiva" expression="d = h − recubrimiento − dᵦ / 2" substitution={`${n(inputs.footingThicknessM)} − ${n(inputs.concreteCoverM)} − ${n(inputs.barDiameterM)} / 2 m`} result={`${n(oneWay.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Contacto de servicio"><Equation name="Carga total de servicio" expression="Pserv,total = Pserv + Wzapata + Wrelleno" substitution={`${n(inputs.axialLoadKn, 2)} + ${n(contact.footingSelfWeightKn, 2)} + ${n(contact.soilCoverWeightKn, 2)} kN`} result={`${n(contact.totalServiceLoadKn, 2)} kN`}/><Equation name="Presión bruta" expression="qbruta = Pserv,total / A" substitution={`${n(contact.totalServiceLoadKn, 2)} / ${n(contact.grossAreaM2)} kN/m²`} result={`${n(contact.grossContactPressureKpa, 2)} kPa`}/><Equation name="Presión neta" expression="qneta = qbruta − qremovido" substitution={`${n(contact.grossContactPressureKpa, 2)} − ${n(inputs.removedOverburdenKpa, 2)} kPa`} result={`${n(contact.netContactPressureKpa, 2)} kPa`}/><Table rows={[['Base comparada', contact.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión comparada', `${n(contact.pressureForComparisonKpa, 2)} kPa`], ['Capacidad admisible declarada', `${n(contact.allowableBearingKpa, 2)} kPa`], ['Utilización', `${n(contact.utilization * 100, 1)}% · ${contact.status === 'pass' ? 'Dentro de la capacidad declarada' : 'Supera la capacidad declarada'}`]]}/></MemoSection>
    <MemoSection number="05" title="Cortante unidireccional"><Equation name="Presión última uniforme" expression="qᵤ = Pᵤ / A" substitution={`${n(oneWay.factoredAxialLoadKn, 2)} / ${n(oneWay.footingAreaM2)} kN/m²`} result={`${n(oneWay.factoredContactPressureKpa, 2)} kPa`}/><DirectionEquation direction="B" area={oneWay.widthDirection.tributaryAreaM2} pressure={oneWay.factoredContactPressureKpa} demand={oneWay.widthDirection.shearDemandKn} projection={oneWay.widthDirection.cantileverProjectionM} loadedLength={oneWay.widthDirection.loadedLengthBeyondSectionM} strip={oneWay.widthDirection.tributaryWidthM}/><DirectionEquation direction="L" area={oneWay.lengthDirection.tributaryAreaM2} pressure={oneWay.factoredContactPressureKpa} demand={oneWay.lengthDirection.shearDemandKn} projection={oneWay.lengthDirection.cantileverProjectionM} loadedLength={oneWay.lengthDirection.loadedLengthBeyondSectionM} strip={oneWay.lengthDirection.tributaryWidthM}/><Equation name="Resistencia de referencia de guía" expression="φVᶜ = φ × vᶜ × b × d" substitution={`φ ${n(oneWayGuide.strengthReductionFactor, 2)} · vᶜ ${n(oneWayGuide.concreteShearStressMpa, 3)} MPa · b · d ${n(oneWayGuide.effectiveDepthM)} m`} result={`B: ${n(oneWayGuide.widthDirection.designShearStrengthKn, 2)} kN · L: ${n(oneWayGuide.lengthDirection.designShearStrengthKn, 2)} kN`}/><ReferenceNote/></MemoSection>
    <MemoSection number="06" title="Punzonamiento"><Equation name="Perímetro crítico de referencia" expression="b₀ = 2 × [(cB + d) + (cL + d)]" substitution={`2 × [(${n(inputs.columnWidthM)} + ${n(oneWay.effectiveDepthM)}) + (${n(inputs.columnLengthM)} + ${n(oneWay.effectiveDepthM)})] m`} result={`${n(punchingGuide.criticalPerimeterM)} m`}/>{punchingDemand ? <Equation name="Demanda con perímetro declarado" expression="Vᵤ = qᵤ × A exterior" substitution={`${n(punchingDemand.factoredContactPressureKpa, 2)} × ${n(punchingDemand.exteriorTributaryAreaM2)} kN/m²·m²`} result={`${n(punchingDemand.shearDemandKn, 2)} kN`}/> : <p className="memo-muted">No se declaró un perímetro independiente para la demanda. La revisión de guía usa el perímetro a d/2.</p>}<Equation name="Resistencia de referencia de guía" expression="φVᶜ = φ × vᶜ × b₀ × d" substitution={`φ 0.75 · vᶜ ${n(punchingGuide.governingConcreteShearStressMpa, 3)} MPa · b₀ ${n(punchingGuide.criticalPerimeterM)} m · d ${n(oneWay.effectiveDepthM)} m`} result={`${n(punchingGuide.designShearStrengthKn, 2)} kN`}/><Table rows={[['Demanda de guía', `${n(punchingGuide.shearDemandKn, 2)} kN`], ['Utilización', `${n(punchingGuide.utilization * 100, 1)}% · ${punchingGuide.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Alternativa gobernante', punchingGuide.governingAlternative === 'square-only' ? 'Columna cuadrada' : punchingGuide.governingAlternative.replace('alternative-', 'Alternativa ')]]}/><ReferenceNote/></MemoSection>
    <MemoSection number="07" title="Flexión"><MomentEquation direction="B" pressure={flexure.factoredContactPressureKpa} strip={flexure.widthDirection.stripWidthM} projection={flexure.widthDirection.cantileverProjectionM} result={flexure.widthDirection.momentDemandKnM}/><MomentEquation direction="L" pressure={flexure.factoredContactPressureKpa} strip={flexure.lengthDirection.stripWidthM} projection={flexure.lengthDirection.cantileverProjectionM} result={flexure.lengthDirection.momentDemandKnM}/></MemoSection>
    <MemoSection number="08" title="Armado inferior de referencia"><Equation name="Área de una barra" expression="Aᵦ = π × dᵦ² / 4" substitution={`π × ${n(inputs.barDiameterM * 1000, 0)}² / 4 mm²`} result={`${n(minimumReinforcement.barAreaMm2, 1)} mm²`}/><Equation name="Acero mínimo de guía por metro" expression="Aₛ,min = 0.0018 × 1000 × h(mm)" substitution={`0.0018 × 1000 × ${n(inputs.footingThicknessM * 1000, 0)} mm`} result={`${n(minimumReinforcement.minimumAreaPerMeterCm2, 2)} cm²/m`}/><Table rows={[['Barras paralelas a B', `${reinforcementLayout.barsParallelToWidth.count} · s real ${n(reinforcementLayout.barsParallelToWidth.actualSpacingM)} m`], ['Barras paralelas a L', `${reinforcementLayout.barsParallelToLength.count} · s real ${n(reinforcementLayout.barsParallelToLength.actualSpacingM)} m`], ['Acero requerido de referencia · B', requiredReinforcement.widthDirection.requiredAreaPerMeterCm2 === null ? 'Sección insuficiente' : `${n(requiredReinforcement.widthDirection.requiredAreaPerMeterCm2, 2)} cm²/m`], ['Acero requerido de referencia · L', requiredReinforcement.lengthDirection.requiredAreaPerMeterCm2 === null ? 'Sección insuficiente' : `${n(requiredReinforcement.lengthDirection.requiredAreaPerMeterCm2, 2)} cm²/m`], ['Acero colocado · B', `${n(reinforcement.widthDirection.providedAreaPerMeterMm2 / 100, 2)} cm²/m`], ['Acero colocado · L', `${n(reinforcement.lengthDirection.providedAreaPerMeterMm2 / 100, 2)} cm²/m`]]}/><p className="memo-formula">Aₛ = 0.85 f′c b d / fy × [1 − √(1 − 2Mᵤ / (0.85 φ f′c b d²))]</p><ReferenceNote/></MemoSection>
    <MemoSection number="09" title="Longitud de desarrollo"><Equation name="Longitud requerida de referencia" expression="lᵈ = fy / (1.4 × √f′c) × dᵦ" substitution={`${n(inputs.steelYieldStrengthMpa, 2)} / (1.4 × √${n(inputs.concreteStrengthMpa, 2)}) × ${n(inputs.barDiameterM)} m`} result={`${n(development.requiredDevelopmentLengthM)} m`}/><Table rows={[['Disponible · B', `${n(development.widthDirection.availableLengthM)} m · ${development.widthDirection.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Disponible · L', `${n(development.lengthDirection.availableLengthM)} m · ${development.lengthDirection.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`]]}/><ReferenceNote/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={report.profile.traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function SourceList({ sources }: { sources: FootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: FootingCalculationReport['profile']['traceability']; sources: FootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function DirectionEquation({ direction, area, pressure, demand, projection, loadedLength, strip }: { direction: string; area: number; pressure: number; demand: number; projection: number; loadedLength: number; strip: number }) { return <div className="calculation-equation"><strong>Dirección {direction}</strong><code>Vᵤ = qᵤ × A tributaria</code><p>Voladizo {n(projection)} m · tramo cargado {n(loadedLength)} m · franja {n(strip)} m · área {n(area)} m²</p><b>{n(pressure, 2)} kN/m² × {n(area)} m² = {n(demand, 2)} kN</b></div> }
function MomentEquation({ direction, pressure, strip, projection, result }: { direction: string; pressure: number; strip: number; projection: number; result: number }) { return <div className="calculation-equation"><strong>Dirección {direction}</strong><code>Mᵤ = qᵤ × b × a² / 2</code><p>{n(pressure, 2)} kN/m² × {n(strip)} m × {n(projection)}² m² / 2</p><b>= {n(result, 2)} kN·m</b></div> }
function ReferenceNote() { return <p className="memo-reference-note">Referencia de guía en validación: este resultado no es una verificación normativa liberada ni una aprobación de diseño.</p> }
