import type { CombinedFootingAnalysis } from '../application/combined-footing-analysis'
import type { CombinedFootingInputs } from '../domain/projects'

type Props = { inputs: CombinedFootingInputs; analysis: CombinedFootingAnalysis | null }
const n = (value: number, decimals = 2) => value.toFixed(decimals)
const sx = (xM: number, lengthM: number) => 90 + 580 * xM / lengthM

export function CombinedFootingLongitudinalSheet({ inputs, analysis }: Props) {
  const x1 = sx(inputs.column1CenterFromLeftM, inputs.footingLengthM)
  const x2 = sx(inputs.column2CenterFromLeftM, inputs.footingLengthM)
  const c1 = Math.max(34, 580 * inputs.column1LengthM / inputs.footingLengthM)
  const c2 = Math.max(34, 580 * inputs.column2LengthM / inputs.footingLengthM)
  const maxMoment = analysis ? Math.max(...analysis.longitudinal.diagram.map((point) => Math.abs(point.momentKnM)), 1) : 1
  const momentPath = analysis ? analysis.longitudinal.diagram.map((point, index) => `${index ? 'L' : 'M'}${sx(point.xM, inputs.footingLengthM)},${352 - point.momentKnM / maxMoment * 34}`).join(' ') : ''
  const qLeft = analysis?.structural.factoredPressureLeftKpa ?? 0
  const qRight = analysis?.structural.factoredPressureRightKpa ?? 0
  const qMax = Math.max(qLeft, qRight, 1)
  const pressureTopLeft = 298 - qLeft / qMax * 42
  const pressureTopRight = 298 - qRight / qMax * 42
  return <figure className="engineering-sheet combined-sheet"><figcaption><span>SECCIÓN LONGITUDINAL A–A</span><strong>Dos columnas y reacción lineal</strong><small>La curva inferior representa el momento de la viga longitudinal.</small></figcaption><svg viewBox="0 0 760 440" role="img" aria-label="Sección longitudinal de zapata combinada"><defs><pattern id="combinedConcrete" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 12 12 0M-3 3 3-3M9 15 15 9" stroke="#c5d0d5" strokeWidth="1"/></pattern><marker id="combinedArrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto"><path d="M0 0 7 3.5 0 7Z" fill="#1b6799"/></marker></defs><path d="M55 160H705" className="ground-line"/><rect x="90" y="176" width="580" height="66" fill="url(#combinedConcrete)" className="footing-line"/><rect x={x1-c1/2} y="68" width={c1} height="108" fill="url(#combinedConcrete)" className="column-line"/><rect x={x2-c2/2} y="68" width={c2} height="108" fill="url(#combinedConcrete)" className="column-line"/><text x={x1} y="92" textAnchor="middle" className="column-label">C1</text><text x={x2} y="92" textAnchor="middle" className="column-label">C2</text><line x1={x1} y1="28" x2={x1} y2="58" className="load-line" markerEnd="url(#combinedArrow)"/><line x1={x2} y1="28" x2={x2} y2="58" className="load-line" markerEnd="url(#combinedArrow)"/><text x={x1+10} y="42" className="load-label">P₁</text><text x={x2+10} y="42" className="load-label">P₂</text>{analysis && <><path d={`M90 298 L90 ${pressureTopLeft} L670 ${pressureTopRight} L670 298 Z`} className="pressure-fill"/><line x1="90" y1={pressureTopLeft} x2="670" y2={pressureTopRight} className="pressure-line"/><text x="98" y="316" className="sheet-notes">qᵤ,izq = {n(qLeft,1)} kPa</text><text x="548" y="316" className="sheet-notes">qᵤ,der = {n(qRight,1)} kPa</text><line x1="90" y1="352" x2="670" y2="352" className="axis-line"/><path d={momentPath} className="moment-line"/><text x="96" y="337" className="sheet-notes">M⁺ = {n(analysis.longitudinal.maximumPositiveMomentKnM,1)} kN·m</text><text x="470" y="337" className="sheet-notes">M⁻ = {n(analysis.longitudinal.minimumNegativeMomentKnM,1)} kN·m</text></>}<line x1="90" y1="410" x2="670" y2="410" className="dimension"/><text x="380" y="430" textAnchor="middle" className="dimension-label">L = {n(inputs.footingLengthM)} m</text><line x1="690" y1="176" x2="690" y2="242" className="dimension"/><text x="680" y="214" textAnchor="end" className="dimension-label">h = {n(inputs.footingThicknessM)} m</text></svg></figure>
}

export function CombinedFootingPlanSheet({ inputs, analysis }: Props) {
  const x1 = sx(inputs.column1CenterFromLeftM, inputs.footingLengthM)
  const x2 = sx(inputs.column2CenterFromLeftM, inputs.footingLengthM)
  const c1L = Math.max(32, 580 * inputs.column1LengthM / inputs.footingLengthM)
  const c2L = Math.max(32, 580 * inputs.column2LengthM / inputs.footingLengthM)
  const c1W = Math.max(34, 236 * inputs.column1WidthM / inputs.footingWidthM)
  const c2W = Math.max(34, 236 * inputs.column2WidthM / inputs.footingWidthM)
  const critical1L = analysis ? Math.max(c1L + 18, 580 * analysis.punching[0].criticalLengthM / inputs.footingLengthM) : 0
  const critical2L = analysis ? Math.max(c2L + 18, 580 * analysis.punching[1].criticalLengthM / inputs.footingLengthM) : 0
  const critical1W = analysis ? Math.max(c1W + 18, 236 * analysis.punching[0].criticalWidthM / inputs.footingWidthM) : 0
  const critical2W = analysis ? Math.max(c2W + 18, 236 * analysis.punching[1].criticalWidthM / inputs.footingWidthM) : 0
  return <figure className="engineering-sheet combined-sheet"><figcaption><span>PLANTA GENERAL</span><strong>Zapata combinada rectangular</strong><small>Columnas interiores alineadas, perímetros críticos y armado preliminar.</small></figcaption><svg viewBox="0 0 760 420" role="img" aria-label="Planta de zapata combinada"><rect x="90" y="78" width="580" height="236" className="footing-line"/><line x1="70" y1="196" x2="690" y2="196" className="axis-line"/><text x="681" y="189" className="axis-label">A</text><rect x={x1-c1L/2} y={196-c1W/2} width={c1L} height={c1W} className="column-line"/><rect x={x2-c2L/2} y={196-c2W/2} width={c2L} height={c2W} className="column-line"/><text x={x1} y="201" textAnchor="middle" className="column-label">C1</text><text x={x2} y="201" textAnchor="middle" className="column-label">C2</text>{analysis && <><rect x={x1-critical1L/2} y={196-critical1W/2} width={critical1L} height={critical1W} className="critical-perimeter"/><rect x={x2-critical2L/2} y={196-critical2W/2} width={critical2L} height={critical2W} className="critical-perimeter"/><text x={x1} y={196-critical1W/2-8} textAnchor="middle" className="callout-title">b₀,1 · η {n(analysis.punching[0].utilization*100,1)}%</text><text x={x2} y={196-critical2W/2-8} textAnchor="middle" className="callout-title">b₀,2 · η {n(analysis.punching[1].utilization*100,1)}%</text></>}{Array.from({length: 9},(_,i)=><line key={`l${i}`} x1="106" y1={94+i*25} x2="654" y2={94+i*25} className="rebar-line secondary"/>)}{Array.from({length: 15},(_,i)=><line key={`t${i}`} x1={108+i*39} y1="92" x2={108+i*39} y2="300" className="rebar-line"/>)}<line x1="90" y1="350" x2="670" y2="350" className="dimension"/><text x="380" y="370" textAnchor="middle" className="dimension-label">L = {n(inputs.footingLengthM)} m</text><line x1="55" y1="78" x2="55" y2="314" className="dimension"/><text x="38" y="198" transform="rotate(-90 38 198)" textAnchor="middle" className="dimension-label">B = {n(inputs.footingWidthM)} m</text><text x={x1} y="399" textAnchor="middle" className="dimension-label">x₁ = {n(inputs.column1CenterFromLeftM)} m</text><text x={x2} y="399" textAnchor="middle" className="dimension-label">x₂ = {n(inputs.column2CenterFromLeftM)} m</text></svg></figure>
}

export function CombinedReinforcementSummary({ inputs, analysis }: Props) {
  if (!analysis) return <section className="sheet-empty">Analiza el caso para revisar el armado combinado.</section>
  const row = (label: string, spacing: number, result: CombinedFootingAnalysis['reinforcement']['longitudinalBottom']) => <div><dt>{label}</dt><dd>Ø{n(inputs.barDiameterM*1000,0)} @ {n(spacing)} m · {n(result.providedAreaPerMeterMm2/100)} cm²/m</dd></div>
  return <section className="strip-rebar-summary"><header><span>ARMADO PRELIMINAR</span><h3>Zonas longitudinales y transversales</h3></header><dl>{row('Longitudinal inferior · M⁺', inputs.longitudinalBottomBarSpacingM, analysis.reinforcement.longitudinalBottom)}{row('Longitudinal superior · M⁻', inputs.longitudinalTopBarSpacingM, analysis.reinforcement.longitudinalTop)}{row('Transversal inferior', inputs.transverseBarSpacingM, analysis.reinforcement.transverse)}<div><dt>Desarrollo requerido</dt><dd>{n(analysis.development.requiredDevelopmentLengthM)} m</dd></div><div><dt>Punzonamiento gobernante</dt><dd>{n(Math.max(...analysis.punching.map((item)=>item.utilization))*100,1)}%</dd></div></dl><p>Distribución preliminar de referencia; no constituye un plano constructivo definitivo.</p></section>
}
