import type { EdgeFootingAnalysis } from '../application/edge-footing-analysis'
import type { EdgeFootingInputs } from '../domain/projects'

type Props = { inputs: EdgeFootingInputs; analysis: EdgeFootingAnalysis | null }
const n = (value: number, decimals = 2) => value.toFixed(decimals)
const sx = (x: number, length: number) => 110 + 540 * x / length

export function EdgeFootingPlanSheet({ inputs, analysis }: Props) {
  const centerY = 195
  const footingHeight = 220
  const columnCenterM = analysis?.geometry.columnCenterFromLeftM ?? (inputs.edgeSide === 'left' ? inputs.columnLengthM / 2 : inputs.footingLengthM - inputs.columnLengthM / 2)
  const columnX = sx(columnCenterM, inputs.footingLengthM)
  const columnLength = Math.max(34, 540 * inputs.columnLengthM / inputs.footingLengthM)
  const columnWidth = Math.max(34, footingHeight * inputs.columnWidthM / inputs.footingWidthM)
  const boundaryX = inputs.edgeSide === 'left' ? 110 : 650
  const resultantX = analysis ? sx(analysis.contact.gross.resultantFromLeftM, inputs.footingLengthM) : null
  return <figure className="engineering-sheet edge-sheet"><figcaption><span>PLANTA GENERAL</span><strong>Zapata aislada excéntrica de borde</strong><small>La columna se centra transversalmente y una cara coincide con el lindero.</small></figcaption><svg viewBox="0 0 760 430" role="img" aria-label="Planta de zapata aislada excéntrica de borde"><rect x="110" y={centerY - footingHeight / 2} width="540" height={footingHeight} className="footing-line"/><line x1="75" y1={centerY} x2="685" y2={centerY} className="axis-line"/><line x1={boundaryX} y1="42" x2={boundaryX} y2="338" className="critical-line"/><text x={inputs.edgeSide === 'left' ? boundaryX + 8 : boundaryX - 8} y="55" textAnchor={inputs.edgeSide === 'left' ? 'start' : 'end'} className="callout-title">LINDERO</text><rect x={columnX - columnLength / 2} y={centerY - columnWidth / 2} width={columnLength} height={columnWidth} className="column-line"/><text x={columnX} y={centerY + 4} textAnchor="middle" className="column-label">C</text>{analysis && <><line x1={resultantX!} y1="62" x2={resultantX!} y2="326" className="load-line"/><text x={resultantX! + (inputs.edgeSide === 'left' ? 7 : -7)} y="76" textAnchor={inputs.edgeSide === 'left' ? 'start' : 'end'} className="load-label">R · e={n(analysis.contact.gross.eccentricityM, 3)} m</text><path d={inputs.edgeSide === 'left' ? `M110 ${centerY - columnWidth / 2 - 20} H${columnX + columnLength / 2 + 22} V${centerY + columnWidth / 2 + 20} H110` : `M650 ${centerY - columnWidth / 2 - 20} H${columnX - columnLength / 2 - 22} V${centerY + columnWidth / 2 + 20} H650`} className="critical-perimeter"/><text x="380" y="330" textAnchor="middle" className="sheet-notes">Punzonamiento de borde · perímetro truncado no evaluado</text></>}<line x1="110" y1="365" x2="650" y2="365" className="dimension"/><text x="380" y="386" textAnchor="middle" className="dimension-label">L = {n(inputs.footingLengthM)} m · dirección excéntrica</text><line x1="78" y1={centerY - footingHeight / 2} x2="78" y2={centerY + footingHeight / 2} className="dimension"/><text x="60" y={centerY} transform={`rotate(-90 60 ${centerY})`} textAnchor="middle" className="dimension-label">B = {n(inputs.footingWidthM)} m</text>{analysis && <text x="380" y="416" textAnchor="middle" className="sheet-notes">A = {n(analysis.geometry.areaM2)} m² · qserv: {n(analysis.contact.grossPressureLeftKpa, 1)} → {n(analysis.contact.grossPressureRightKpa, 1)} kPa</text>}</svg></figure>
}

export function EdgeFootingLongitudinalSheet({ inputs, analysis }: Props) {
  const columnCenterM = analysis?.geometry.columnCenterFromLeftM ?? (inputs.edgeSide === 'left' ? inputs.columnLengthM / 2 : inputs.footingLengthM - inputs.columnLengthM / 2)
  const columnX = sx(columnCenterM, inputs.footingLengthM)
  const columnLength = Math.max(40, 540 * inputs.columnLengthM / inputs.footingLengthM)
  const qLeft = analysis?.structural.factored.pressureLeftKpa ?? 0
  const qRight = analysis?.structural.factored.pressureRightKpa ?? 0
  const qMax = Math.max(qLeft, qRight, 1)
  const yLeft = 306 - 55 * qLeft / qMax
  const yRight = 306 - 55 * qRight / qMax
  const maxMoment = analysis ? Math.max(...analysis.longitudinal.diagram.map((point) => Math.abs(point.momentKnM)), 1) : 1
  const momentPath = analysis ? analysis.longitudinal.diagram.map((point, index) => `${index ? 'L' : 'M'}${sx(point.xM, inputs.footingLengthM)},${370 - point.momentKnM / maxMoment * 38}`).join(' ') : ''
  return <figure className="engineering-sheet edge-sheet"><figcaption><span>SECCIÓN LONGITUDINAL A–A</span><strong>Excentricidad y presión lineal</strong><small>Fuerza y momento se equilibran sin admitir tracción del suelo.</small></figcaption><svg viewBox="0 0 760 455" role="img" aria-label="Sección longitudinal de zapata excéntrica de borde"><defs><marker id="edgeArrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto"><path d="M0 0 7 3.5 0 7Z" fill="#1b6799"/></marker></defs><line x1="75" y1="160" x2="685" y2="160" className="ground-line"/><rect x="110" y="178" width="540" height="66" className="footing-line"/><rect x={columnX - columnLength / 2} y="70" width={columnLength} height="108" className="column-line"/><line x1={columnX} y1="28" x2={columnX} y2="60" className="load-line" markerEnd="url(#edgeArrow)"/><text x={columnX + (inputs.edgeSide === 'left' ? 10 : -10)} y="43" textAnchor={inputs.edgeSide === 'left' ? 'start' : 'end'} className="load-label">P</text><line x1={inputs.edgeSide === 'left' ? 110 : 650} y1="45" x2={inputs.edgeSide === 'left' ? 110 : 650} y2="252" className="critical-line"/><text x={inputs.edgeSide === 'left' ? 118 : 642} y="58" textAnchor={inputs.edgeSide === 'left' ? 'start' : 'end'} className="callout-title">LINDERO</text>{analysis && <><path d={`M110 306 L110 ${yLeft} L650 ${yRight} L650 306 Z`} className="pressure-fill"/><line x1="110" y1={yLeft} x2="650" y2={yRight} className="pressure-line"/><text x="116" y="325" className="sheet-notes">qᵤ,izq = {n(qLeft, 1)} kPa</text><text x="522" y="325" className="sheet-notes">qᵤ,der = {n(qRight, 1)} kPa</text><line x1="110" y1="370" x2="650" y2="370" className="axis-line"/><path d={momentPath} className="moment-line"/><text x="116" y="357" className="sheet-notes">M cara gob. = {n(analysis.longitudinal.governingFlexureDemandKnM, 1)} kN·m</text><text x="500" y="357" className="sheet-notes">V(L)={n(analysis.longitudinal.endShearKn, 4)}</text></>}<line x1="110" y1="425" x2="650" y2="425" className="dimension"/><text x="380" y="447" textAnchor="middle" className="dimension-label">L = {n(inputs.footingLengthM)} m · |eᵤ| = {analysis ? n(Math.abs(analysis.structural.factored.eccentricityM), 3) : '—'} m</text></svg></figure>
}

export function EdgeReinforcementSummary({ inputs, analysis }: Props) {
  if (!analysis) return <section className="sheet-empty">Analiza el caso para revisar el armado de la zapata excéntrica.</section>
  const status = (value: string) => value === 'meets-guide-reference' ? 'Dentro de referencia' : value === 'section-insufficient' ? 'Sección insuficiente' : 'Requiere ajuste'
  return <section className="strip-rebar-summary"><header><span>ARMADO PRELIMINAR</span><h3>Dirección excéntrica y paralela al lindero</h3></header><dl><div><dt>Longitudinal</dt><dd>Ø{n(inputs.barDiameterM * 1000, 0)} @ {n(inputs.longitudinalBarSpacingM)} m · {n(analysis.reinforcement.longitudinal.providedAreaPerMeterMm2 / 100)} cm²/m</dd></div><div><dt>Estado longitudinal</dt><dd>{status(analysis.reinforcement.longitudinal.status)}</dd></div><div><dt>Transversal</dt><dd>Ø{n(inputs.barDiameterM * 1000, 0)} @ {n(inputs.transverseBarSpacingM)} m · {n(analysis.reinforcement.transverse.providedAreaPerMeterMm2 / 100)} cm²/m</dd></div><div><dt>Estado transversal</dt><dd>{status(analysis.reinforcement.transverse.status)}</dd></div><div><dt>Desarrollo requerido</dt><dd>{n(analysis.development.requiredDevelopmentLengthM)} m</dd></div><div><dt>Punzonamiento</dt><dd>No evaluado · perímetro de borde</dd></div></dl><p>La distribución es preliminar y no constituye plano constructivo ni resuelve el anclaje junto al lindero.</p></section>
}
