import type { MatFootingAnalysis } from '../application/mat-footing-analysis'
import type { MatFootingInputs } from '../domain/projects'

type Props = { inputs: MatFootingInputs; analysis: MatFootingAnalysis | null }
const n = (value: number, decimals = 2) => value.toFixed(decimals)

export function MatFootingPlanSheet({ inputs, analysis }: Props) {
  const sx = (x: number) => 120 + 520 * x / inputs.footingLengthM
  const sy = (y: number) => 330 - 270 * y / inputs.footingWidthM
  const q = analysis?.contact.gross.cornerPressuresKpa
  return <figure className="engineering-sheet mat-sheet"><figcaption><span>PLANTA GENERAL</span><strong>Losa de cimentación · contacto biaxial</strong><small>{inputs.columns.length} columnas · coordenadas desde la esquina inferior izquierda.</small></figcaption><svg viewBox="0 0 760 440" role="img" aria-label="Planta de losa de cimentación"><defs><linearGradient id="mat-pressure" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stopColor="#dff3ec"/><stop offset="1" stopColor="#efb277"/></linearGradient></defs><rect x="120" y="60" width="520" height="270" fill={analysis ? 'url(#mat-pressure)' : 'transparent'} className="footing-line"/><line x1="120" y1="195" x2="640" y2="195" className="axis-line"/><line x1="380" y1="60" x2="380" y2="330" className="axis-line"/>{inputs.columns.map((column) => { const width = Math.max(20, 520 * column.lengthM / inputs.footingLengthM); const height = Math.max(20, 270 * column.widthM / inputs.footingWidthM); return <g key={column.id}><rect x={sx(column.centerXM)-width/2} y={sy(column.centerYM)-height/2} width={width} height={height} className="column-line"/><text x={sx(column.centerXM)} y={sy(column.centerYM)+4} textAnchor="middle" className="column-label">{column.id}</text><text x={sx(column.centerXM)} y={sy(column.centerYM)-height/2-7} textAnchor="middle" className="sheet-notes">{n(column.serviceLoadKn,0)}</text></g>})}{q && <><text x="130" y="80" className="sheet-notes">qTL {n(q.topLeft,1)}</text><text x="630" y="80" textAnchor="end" className="sheet-notes">qTR {n(q.topRight,1)}</text><text x="130" y="320" className="sheet-notes">qBL {n(q.bottomLeft,1)}</text><text x="630" y="320" textAnchor="end" className="sheet-notes">qBR {n(q.bottomRight,1)}</text><text x="380" y="360" textAnchor="middle" className="sheet-notes">κ = {n(analysis!.contact.gross.kernInteraction,3)} · q en kPa</text></>}<line x1="120" y1="385" x2="640" y2="385" className="dimension"/><text x="380" y="407" textAnchor="middle" className="dimension-label">L = {n(inputs.footingLengthM)} m</text><line x1="85" y1="60" x2="85" y2="330" className="dimension"/><text x="62" y="195" transform="rotate(-90 62 195)" textAnchor="middle" className="dimension-label">B = {n(inputs.footingWidthM)} m</text></svg></figure>
}

function ProjectionSheet({ inputs, analysis, axis }: Props & { axis: 'x' | 'y' }) {
  const projection = analysis?.projections[axis]
  const length = axis === 'x' ? inputs.footingLengthM : inputs.footingWidthM
  const sx = (value: number) => 105 + 550 * value / length
  const qMax = Math.max(projection?.pressureStartKpa ?? 0, projection?.pressureEndKpa ?? 0, 1)
  const yq = (q: number) => 310 - 60*q/qMax
  const maxMoment = Math.max(...(projection?.diagram.map(({ momentKnM }) => Math.abs(momentKnM)) ?? [1]), 1)
  const path = projection?.diagram.map((point, index) => `${index ? 'L' : 'M'}${sx(point.coordinateM)},${375-point.momentKnM/maxMoment*34}`).join(' ') ?? ''
  return <figure className="engineering-sheet mat-sheet"><figcaption><span>PROYECCIÓN {axis.toUpperCase()}</span><strong>Auditoría de equilibrio global</strong><small>No es una franja de diseño estructural de placa.</small></figcaption><svg viewBox="0 0 760 440" role="img" aria-label={`Proyección de equilibrio ${axis}`}><rect x="105" y="180" width="550" height="55" className="footing-line"/>{projection?.projectedColumns.map((column, index) => <g key={`${column.id}-${index}`}><line x1={sx(column.coordinateM)} y1="70" x2={sx(column.coordinateM)} y2="170" className="load-line"/><text x={sx(column.coordinateM)+5} y="62" className="load-label">{column.id} · {n(column.loadKn,0)}</text></g>)}{projection && <><path d={`M105 310 L105 ${yq(projection.pressureStartKpa)} L655 ${yq(projection.pressureEndKpa)} L655 310 Z`} className="pressure-fill"/><line x1="105" y1={yq(projection.pressureStartKpa)} x2="655" y2={yq(projection.pressureEndKpa)} className="pressure-line"/><text x="110" y="332" className="sheet-notes">q₀={n(projection.pressureStartKpa,1)} kPa</text><text x="650" y="332" textAnchor="end" className="sheet-notes">q₁={n(projection.pressureEndKpa,1)} kPa</text><line x1="105" y1="375" x2="655" y2="375" className="axis-line"/><path d={path} className="moment-line"/></>}<text x="380" y="420" textAnchor="middle" className="dimension-label">{axis === 'x' ? 'L' : 'B'}={n(length)} m · Vfin={projection ? n(projection.endShearKn,6) : '—'} kN · Mfin={projection ? n(projection.endMomentKnM,6) : '—'} kN·m</text></svg></figure>
}

export function MatFootingProjectionSheets(props: Props) { return <div className="new-section-grid"><ProjectionSheet {...props} axis="x"/><ProjectionSheet {...props} axis="y"/></div> }

export function MatFootingScopeSummary({ analysis }: { analysis: MatFootingAnalysis | null }) {
  return <section className="strip-rebar-summary"><header><span>ALCANCE ESTRUCTURAL</span><h3>Lo calculado y lo separado</h3></header><dl><div><dt>Contacto</dt><dd>{analysis ? 'Calculado · plano biaxial' : 'Pendiente'}</dd></div><div><dt>Asentamiento</dt><dd>{analysis?.settlement.status === 'calculated' ? 'Calculado · pantalla Winkler' : 'No evaluado'}</dd></div><div><dt>Equilibrio</dt><dd>{analysis ? 'Calculado en X y Y' : 'Pendiente'}</dd></div><div><dt>Placa</dt><dd>No evaluada</dd></div><div><dt>Punzonamiento</dt><dd>No evaluado</dd></div><div><dt>Armado</dt><dd>No evaluado</dd></div></dl><p>La aplicación no convierte las proyecciones globales en momentos de diseño. Hace falta un modelo de placa–suelo antes de dimensionar acero.</p></section>
}
