import type { StripFootingAnalysis } from '../application/strip-footing-analysis'
import type { StripFootingInputs } from '../domain/projects'

type Props = { inputs: StripFootingInputs; analysis: StripFootingAnalysis | null }
const n = (value: number, decimals = 2) => value.toFixed(decimals)

export function StripFootingSectionSheet({ inputs, analysis }: Props) {
  const footingLeft = 120
  const footingWidth = 520
  const wallWidth = Math.max(45, Math.min(footingWidth * .7, footingWidth * inputs.wallThicknessM / inputs.footingWidthM))
  const wallLeft = 380 - wallWidth / 2
  const effectiveOffset = analysis ? Math.min((analysis.structural.effectiveDepthM / inputs.footingWidthM) * footingWidth, 150) : 0
  return <figure className="engineering-sheet strip-sheet"><figcaption><span>SECCIÓN T–T · FRANJA DE 1.00 m</span><strong>Zapata corrida bajo muro centrado</strong><small>Geometría transversal, presión uniforme y secciones críticas.</small></figcaption><svg viewBox="0 0 760 400" role="img" aria-label="Sección de zapata corrida bajo muro"><defs><pattern id="stripConcrete" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 12 12 0M-3 3 3-3M9 15 15 9" stroke="#c5d0d5" strokeWidth="1"/></pattern><marker id="stripArrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto"><path d="M0 0 7 3.5 0 7Z" fill="#1b6799"/></marker></defs><path d="M60 198H700" className="ground-line"/><text x="62" y="188" className="ground-label">NIVEL DE TERRENO</text><rect x={footingLeft} y="250" width={footingWidth} height="76" fill="url(#stripConcrete)" className="footing-line"/><rect x={wallLeft} y="85" width={wallWidth} height="165" fill="url(#stripConcrete)" className="column-line"/><text x="380" y="115" textAnchor="middle" className="column-label">MURO CONTINUO</text><line x1="380" y1="38" x2="380" y2="76" className="load-line" markerEnd="url(#stripArrow)"/><text x="395" y="55" className="load-label">P / m</text>{analysis && <><line x1={wallLeft - effectiveOffset} y1="238" x2={wallLeft - effectiveOffset} y2="338" className="critical-line"/><line x1={wallLeft + wallWidth + effectiveOffset} y1="238" x2={wallLeft + wallWidth + effectiveOffset} y2="338" className="critical-line"/><text x={wallLeft - effectiveOffset} y="350" textAnchor="middle" className="callout-title">d</text><text x={wallLeft + wallWidth + effectiveOffset} y="350" textAnchor="middle" className="callout-title">d</text></>}<line x1={footingLeft + 18} y1="310" x2={footingLeft + footingWidth - 18} y2="310" className="rebar-line"/>{Array.from({ length: 11 }, (_, index) => <circle key={index} cx={footingLeft + 25 + index * ((footingWidth - 50) / 10)} cy="310" r="4" className="section-bar"/>)}<line x1={footingLeft} y1="365" x2={footingLeft + footingWidth} y2="365" className="dimension"/><text x="380" y="384" textAnchor="middle" className="dimension-label">B = {n(inputs.footingWidthM)} m</text><line x1="675" y1="250" x2="675" y2="326" className="dimension"/><text x="690" y="291" className="dimension-label">h = {n(inputs.footingThicknessM)} m</text>{analysis && <><text x="92" y="235" className="sheet-notes">qᵤ = {n(analysis.structural.factoredContactPressureKpa, 1)} kPa</text><text x="92" y="355" className="sheet-notes">Vᵤ = {n(analysis.structural.oneWayShearDemandKnPerM, 1)} kN/m</text><text x="510" y="355" className="sheet-notes">Mᵤ = {n(analysis.structural.flexureDemandKnMPerM, 1)} kN·m/m</text></>}</svg></figure>
}

export function StripFootingPlanSheet({ inputs, analysis }: Props) {
  const transverseBars = Array.from({ length: 7 }, (_, index) => 125 + index * 80)
  const longitudinalBars = Array.from({ length: 9 }, (_, index) => 78 + index * 30)
  return <figure className="engineering-sheet strip-sheet"><figcaption><span>PLANTA · TRAMO REPRESENTATIVO</span><strong>Continuidad y armado inferior</strong><small>La longitud dibujada es representativa; el cálculo corresponde a una franja de 1.00 m.</small></figcaption><svg viewBox="0 0 760 400" role="img" aria-label="Planta de zapata corrida"><rect x="90" y="62" width="580" height="276" className="footing-line"/><rect x="90" y="177" width="580" height="46" className="column-line"/><text x="380" y="170" textAnchor="middle" className="column-label">MURO CONTINUO · EJE LONGITUDINAL</text>{transverseBars.map((x) => <line key={x} x1={x} y1="76" x2={x} y2="324" className="rebar-line"/>)}{longitudinalBars.map((y) => <line key={y} x1="104" y1={y} x2="656" y2={y} className="rebar-line secondary"/>)}<line x1="64" y1="62" x2="64" y2="338" className="dimension"/><text x="48" y="205" textAnchor="middle" transform="rotate(-90 48 205)" className="dimension-label">B = {n(inputs.footingWidthM)} m</text><line x1="90" y1="365" x2="670" y2="365" className="dimension"/><text x="380" y="384" textAnchor="middle" className="dimension-label">CONTINUIDAD LONGITUDINAL</text>{analysis && <><rect x="510" y="88" width="138" height="65" className={analysis.contact.status === 'pass' ? 'state-box meets-guide-reference' : 'state-box'}/><text x="522" y="108" className="state-title">CONTACTO</text><text x="522" y="128" className="state-value">{n(analysis.contact.pressureForComparisonKpa, 1)} / {n(inputs.allowableBearingKpa, 1)} kPa</text><text x="522" y="144" className="state-value">η = {n(analysis.contact.utilization * 100, 1)}%</text></>}</svg></figure>
}

export function StripReinforcementSummary({ inputs, analysis }: Props) {
  if (!analysis) return <section className="sheet-empty">Analiza el caso para revisar el armado por metro.</section>
  const governing = analysis.reinforcement.transverseGoverningAreaPerMeterMm2
  return <section className="strip-rebar-summary"><header><span>ARMADO PRELIMINAR</span><h3>Distribución por metro lineal</h3></header><dl><div><dt>Transversal · principal</dt><dd>Ø{n(inputs.barDiameterM * 1000, 0)} @ {n(inputs.transverseBarSpacingM)} m</dd></div><div><dt>Área colocada transversal</dt><dd>{n(analysis.reinforcement.transverseProvidedAreaPerMeterMm2 / 100)} cm²/m</dd></div><div><dt>Área gobernante transversal</dt><dd>{governing === null ? 'Sección insuficiente' : `${n(governing / 100)} cm²/m`}</dd></div><div><dt>Longitudinal · distribución</dt><dd>Ø{n(inputs.barDiameterM * 1000, 0)} @ {n(inputs.longitudinalBarSpacingM)} m</dd></div><div><dt>Área colocada longitudinal</dt><dd>{n(analysis.reinforcement.longitudinalProvidedAreaPerMeterMm2 / 100)} cm²/m</dd></div><div><dt>Punzonamiento</dt><dd>No aplica al modelo continuo bajo muro</dd></div></dl><p>Distribución de referencia; no constituye un plano constructivo definitivo.</p></section>
}
