import type { EdgeFootingAnalysis } from '../../application/edge-footing-analysis'
import type { EdgeFootingInputs } from '../../domain/projects'
import type { EdgeFootingCalculationReport } from '../../reports/edge-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: EdgeFootingAnalysis | null; inputs: EdgeFootingInputs; report: EdgeFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)
const area = (value: number | null) => value === null ? 'Sección insuficiente' : `${n(value / 100, 2)} cm²/m`

export function EdgeCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata excéntrica para generar la memoria completa.</p></section>
  const traceability = report.profile.traceability.filter((item) => item.appliesTo.includes('edge'))
  const gross = analysis.contact.gross
  const factored = analysis.structural.factored
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA EXCÉNTRICA DE BORDE</span><h2>{report.project.name}</h2><p>Memoria de contacto completo y excentricidad uniaxial · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, modelo y fuentes"><Table rows={[["Perfil técnico", report.profile.label], ['Modelo', 'Zapata aislada rectangular excéntrica'], ['Orientación', `Borde ${inputs.edgeSide === 'left' ? 'izquierdo' : 'derecho'}`], ['Contacto', 'Presión longitudinal lineal y compresión en toda la base'], ['Punzonamiento', 'No evaluado para perímetro de borde']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría, borde y profundidad efectiva"><Equation name="Área de apoyo" expression="A = B·L" substitution={`${n(inputs.footingWidthM)}×${n(inputs.footingLengthM)}`} result={`${n(analysis.geometry.areaM2)} m²`}/><Equation name="Centroide de la base" expression="xc = L/2" substitution={`${n(inputs.footingLengthM)}/2`} result={`${n(analysis.geometry.centroidFromLeftM)} m`}/><Equation name="Centro de columna" expression={inputs.edgeSide === 'left' ? 'xp = cL/2' : 'xp = L−cL/2'} substitution={inputs.edgeSide === 'left' ? `${n(inputs.columnLengthM)}/2` : `${n(inputs.footingLengthM)}−${n(inputs.columnLengthM)}/2`} result={`${n(analysis.geometry.columnCenterFromLeftM)} m`}/><Equation name="Caras de columna" expression="xizq=xp−cL/2; xder=xp+cL/2" substitution="La cara exterior coincide exactamente con el lindero seleccionado." result={`${n(analysis.geometry.columnLeftFaceM)} → ${n(analysis.geometry.columnRightFaceM)} m`}/><Equation name="Profundidad efectiva" expression="d = h−c−dᵦ/2" substitution={`${n(inputs.footingThicknessM)}−${n(inputs.concreteCoverM)}−${n(inputs.barDiameterM)}/2`} result={`${n(analysis.structural.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Equilibrio y contacto de servicio"><Equation name="Peso propio" expression="Wz = A·h·γc" substitution={`${n(analysis.geometry.areaM2)}×${n(inputs.footingThicknessM)}×${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.contact.footingSelfWeightKn,2)} kN`}/><Equation name="Carga vertical total" expression="P = Pcol+Wz+Wr" substitution={`${n(inputs.serviceAxialLoadKn,2)}+${n(analysis.contact.footingSelfWeightKn,2)}+${n(analysis.contact.soilCoverWeightKn,2)}`} result={`${n(gross.totalLoadKn,2)} kN`}/><Equation name="Momento respecto del centroide" expression="M = Pcol(xp−xc)" substitution={`${n(inputs.serviceAxialLoadKn,2)}×(${n(analysis.geometry.columnCenterFromLeftM)}−${n(analysis.geometry.centroidFromLeftM)})`} result={`${n(gross.momentAboutCentroidKnM,3)} kN·m`}/><Equation name="Excentricidad" expression="e = M/P" substitution={`${n(gross.momentAboutCentroidKnM,3)}/${n(gross.totalLoadKn,3)}`} result={`${n(gross.eccentricityM,5)} m`}/><Equation name="Presiones extremas" expression="qizq=qprom(1−6e/L); qder=qprom(1+6e/L)" substitution={`qprom=${n(gross.averagePressureKpa,3)} kPa; 6e/L=${n(6 * gross.eccentricityM / inputs.footingLengthM,5)}`} result={`${n(gross.pressureLeftKpa,3)} → ${n(gross.pressureRightKpa,3)} kPa`}/><Table rows={[["Control del tercio central", `|e|=${n(Math.abs(gross.eccentricityM),4)} m ≤ L/6=${n(gross.middleThirdLimitM,4)} m`], ['Margen hasta el límite', `${n(gross.middleThirdMarginM,4)} m`], ['Base comparada', inputs.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión máxima comparada', `${n(analysis.contact.maximumPressureForComparisonKpa,2)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa,2)} kPa`], ['Utilización', `${n(analysis.contact.utilization * 100,1)}% · ${analysis.contact.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada'}`]]}/></MemoSection>
    <MemoSection number="05" title="Presión última y equilibrio longitudinal"><Equation name="Excentricidad última" expression="eᵤ = xp−xc" substitution={`${n(analysis.geometry.columnCenterFromLeftM)}−${n(analysis.geometry.centroidFromLeftM)}`} result={`${n(factored.eccentricityM,5)} m`}/><Equation name="Presión promedio última" expression="q̄ᵤ = Pᵤ/(B·L)" substitution={`${n(inputs.factoredAxialLoadKn,2)}/(${n(inputs.footingWidthM)}×${n(inputs.footingLengthM)})`} result={`${n(factored.averagePressureKpa,3)} kPa`}/><Equation name="Presión última lineal" expression="qᵤ(x)=qᵤ,izq+(qᵤ,der−qᵤ,izq)x/L" substitution={`qᵤ,izq=${n(factored.pressureLeftKpa,3)}; qᵤ,der=${n(factored.pressureRightKpa,3)}`} result={`qmin=${n(factored.minimumPressureKpa,3)} kPa`}/><Equation name="Reacción longitudinal" expression="w(x)=Bqᵤ(x)=w₀+kx" substitution={`w₀=${n(analysis.longitudinal.distributedReactionKnM.intercept,3)}; k=${n(analysis.longitudinal.distributedReactionKnM.slope,3)}`} result="kN/m"/><Equation name="Cortante" expression="V(x)=w₀x+kx²/2−Pᵤ" substitution="El término de la columna entra después de cruzar xp." result={`V(L)=${n(analysis.longitudinal.endShearKn,8)} kN`}/><Equation name="Momento" expression="M(x)=w₀x²/2+kx³/6−Pᵤ(x−xp)" substitution="El término puntual se aplica para x≥xp." result={`M(L)=${n(analysis.longitudinal.endMomentKnM,8)} kN·m`}/></MemoSection>
    <MemoSection number="06" title="Cortante unidireccional"><Table rows={analysis.longitudinal.criticalShearSections.length ? analysis.longitudinal.criticalShearSections.map((section) => [section.label, `x=${n(section.xM)} m · Vᵤ=${n(section.shearKn,2)} kN`]) : [['Secciones longitudinales a d', 'Ninguna queda dentro del voladizo; demanda longitudinal igual a cero']]}/><Equation name="Cortante transversal" expression="Vᵤ,t=(∫qᵤdx)·máx(a−d,0)" substitution={`${n(analysis.transverse.integratedPressureKnM,3)}×${n(analysis.transverse.loadedLengthBeyondCriticalSectionM)}`} result={`${n(analysis.transverse.oneWayShearDemandKn,2)} kN`}/><Table rows={[["Referencia longitudinal", `φVᶜ=${n(analysis.shearReference.longitudinal.designShearStrengthKn,2)} kN · η=${n(analysis.shearReference.longitudinal.utilization * 100,1)}%`], ['Referencia transversal', `φVᶜ=${n(analysis.shearReference.transverse.designShearStrengthKn,2)} kN · η=${n(analysis.shearReference.transverse.utilization * 100,1)}%`]]}/></MemoSection>
    <MemoSection number="07" title="Punzonamiento de borde"><Table rows={[["Estado", 'No evaluado'], ['Motivo', analysis.punching.reason], ['Decisión de seguridad', 'No se reutiliza el perímetro cerrado ni la resistencia de columna interior'], ['Acción necesaria', 'Revisión especializada con referencia específica para columna de borde']]}/><p className="memo-muted">Esta exclusión es parte del resultado técnico, no un cálculo omitido silenciosamente.</p></MemoSection>
    <MemoSection number="08" title="Flexión y armado"><Equation name="Momento en cara izquierda" expression="Mizq=∫₀ˣᶠ qᵤ(x)B(xf−x)dx" substitution={`xf=${n(analysis.geometry.columnLeftFaceM)} m`} result={`${n(analysis.longitudinal.leftFaceFlexureDemandKnM,3)} kN·m`}/><Equation name="Momento en cara derecha" expression="Mder=∫ₓᶠᴸ qᵤ(x)B(x−xf)dx" substitution={`xf=${n(analysis.geometry.columnRightFaceM)} m`} result={`${n(analysis.longitudinal.rightFaceFlexureDemandKnM,3)} kN·m`}/><Equation name="Flexión transversal" expression="Mᵤ,t=(∫qᵤdx)·a²/2" substitution={`${n(analysis.transverse.integratedPressureKnM,3)}×${n(analysis.transverse.cantileverProjectionM)}²/2`} result={`${n(analysis.transverse.flexureDemandKnM,3)} kN·m`}/><Equation name="Acero mínimo" expression="Aₛ,min=0.0018×1000×h(mm)" substitution={`0.0018×1000×${n(inputs.footingThicknessM * 1000,0)}`} result={`${n(analysis.minimumReinforcement.minimumAreaPerMeterCm2,2)} cm²/m`}/><Table rows={[["Longitudinal requerido", area(analysis.reinforcement.longitudinal.governingAreaPerMeterMm2)], ['Longitudinal colocado', area(analysis.reinforcement.longitudinal.providedAreaPerMeterMm2)], ['Transversal requerido', area(analysis.reinforcement.transverse.governingAreaPerMeterMm2)], ['Transversal colocado', area(analysis.reinforcement.transverse.providedAreaPerMeterMm2)]]}/></MemoSection>
    <MemoSection number="09" title="Desarrollo y exclusiones"><Equation name="Longitud requerida" expression="lᵈ=fy/(1.4√f′c)·dᵦ" substitution={`${n(inputs.steelYieldStrengthMpa,2)}/(1.4√${n(inputs.concreteStrengthMpa,2)})×${n(inputs.barDiameterM)}`} result={`${n(analysis.development.requiredDevelopmentLengthM)} m`}/><Table rows={[["Disponible longitudinal", `${n(analysis.development.longitudinal.availableLengthM)} m · ${analysis.development.longitudinal.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Disponible transversal', `${n(analysis.development.transverse.availableLengthM)} m · ${analysis.development.transverse.status === 'meets-guide-reference' ? 'Dentro de referencia' : 'Requiere ajuste'}`], ['Contacto parcial', 'Bloqueado'], ['Momento adicional, fuerza horizontal o excentricidad biaxial', 'Fuera de alcance'], ['Asentamientos', 'Revisión externa del estudio geotécnico']]}/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value], index) => <div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: EdgeFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: EdgeFootingCalculationReport['profile']['traceability']; sources: EdgeFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
