import type { CornerFootingAnalysis } from '../../application/corner-footing-analysis'
import type { CornerFootingInputs } from '../../domain/projects'
import type { CornerFootingCalculationReport } from '../../reports/corner-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: CornerFootingAnalysis | null; inputs: CornerFootingInputs; report: CornerFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)
const area = (value: number | null) => value === null ? 'Sección insuficiente' : `${n(value / 100, 2)} cm²/m`
const cornerLabel: Record<CornerFootingInputs['cornerPosition'], string> = { 'bottom-left': 'inferior izquierda', 'bottom-right': 'inferior derecha', 'top-left': 'superior izquierda', 'top-right': 'superior derecha' }

export function CornerCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata de esquina para generar la memoria completa.</p></section>
  const traceability = report.profile.traceability.filter((item) => item.appliesTo.includes('corner'))
  const gross = analysis.contact.gross
  const factored = analysis.structural.factored
  const corners = (values: typeof gross.cornerPressuresKpa) => [["Inferior izquierda", `${n(values.bottomLeft)} kPa`], ["Inferior derecha", `${n(values.bottomRight)} kPa`], ["Superior izquierda", `${n(values.topLeft)} kPa`], ["Superior derecha", `${n(values.topRight)} kPa`]] as Array<[string, string]>
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA DE ESQUINA</span><h2>{report.project.name}</h2><p>Memoria de contacto completo y excentricidad biaxial · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, alcance y fuentes"><Table rows={[["Perfil técnico", report.profile.label], ['Modelo', 'Base rectangular rígida con columna en esquina'], ['Orientación', cornerLabel[inputs.cornerPosition]], ['Contacto', 'Plano lineal y compresión en las cuatro esquinas'], ['Derivación', 'AXC-CORNER-DER-001'], ['Punzonamiento', 'No evaluado · perímetro truncado en dos direcciones']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Geometría y posición"><Equation name="Área" expression="A = B·L" substitution={`${n(inputs.footingWidthM)}×${n(inputs.footingLengthM)}`} result={`${n(analysis.geometry.areaM2, 6)} m²`}/><Equation name="Centroide" expression="xc=L/2; yc=B/2" substitution={`${n(inputs.footingLengthM)}/2; ${n(inputs.footingWidthM)}/2`} result={`(${n(analysis.geometry.centroidXM, 4)}, ${n(analysis.geometry.centroidYM, 4)}) m`}/><Equation name="Centro de columna" expression="xp,yp según las dos caras alineadas" substitution={cornerLabel[inputs.cornerPosition]} result={`(${n(analysis.geometry.columnCenterXM, 4)}, ${n(analysis.geometry.columnCenterYM, 4)}) m`}/><Equation name="Profundidad efectiva" expression="d=h−c−dᵦ/2" substitution={`${n(inputs.footingThicknessM)}−${n(inputs.concreteCoverM)}−${n(inputs.barDiameterM)}/2`} result={`${n(analysis.structural.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Cargas y momentos de servicio"><Equation name="Peso propio" expression="Wz=A·h·γc" substitution={`${n(analysis.geometry.areaM2,6)}×${n(inputs.footingThicknessM)}×${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.contact.footingSelfWeightKn,4)} kN`}/><Equation name="Relleno" expression="Wr=A·zr·γr" substitution={`${n(analysis.geometry.areaM2,6)}×${n(inputs.soilCoverDepthM)}×${n(inputs.soilUnitWeightKnM3)}`} result={`${n(analysis.contact.soilCoverWeightKn,4)} kN`}/><Equation name="Carga total" expression="P=Pcol+Wz+Wr" substitution={`${n(inputs.serviceAxialLoadKn)}+${n(analysis.contact.footingSelfWeightKn)}+${n(analysis.contact.soilCoverWeightKn)}`} result={`${n(gross.totalLoadKn,4)} kN`}/><Equation name="Momento respecto de Y" expression="My=Pcol(xp−xc)" substitution={`${n(inputs.serviceAxialLoadKn)}(${n(analysis.geometry.columnCenterXM,4)}−${n(analysis.geometry.centroidXM,4)})`} result={`${n(gross.momentYKnM,4)} kN·m`}/><Equation name="Momento respecto de X" expression="Mx=Pcol(yp−yc)" substitution={`${n(inputs.serviceAxialLoadKn)}(${n(analysis.geometry.columnCenterYM,4)}−${n(analysis.geometry.centroidYM,4)})`} result={`${n(gross.momentXKnM,4)} kN·m`}/></MemoSection>
    <MemoSection number="05" title="Excentricidades y núcleo central biaxial"><Equation name="Excentricidad X" expression="ex=My/P" substitution={`${n(gross.momentYKnM,4)}/${n(gross.totalLoadKn,4)}`} result={`${n(gross.eccentricityXM,6)} m`}/><Equation name="Excentricidad Y" expression="ey=Mx/P" substitution={`${n(gross.momentXKnM,4)}/${n(gross.totalLoadKn,4)}`} result={`${n(gross.eccentricityYM,6)} m`}/><Equation name="Interacción del núcleo" expression="κ=6|ex|/L+6|ey|/B" substitution={`${n(Math.abs(gross.normalizedEccentricityX),6)}+${n(Math.abs(gross.normalizedEccentricityY),6)}`} result={`${n(gross.kernInteraction,6)} ≤ 1.000000`}/><Table rows={[["Margen hasta pérdida de contacto", n(gross.kernMargin,6)], ['Lectura correcta', 'La suma biaxial controla; no son dos tercios centrales independientes']]}/></MemoSection>
    <MemoSection number="06" title="Plano de presiones de servicio"><Equation name="Presión promedio" expression="q̄=P/(B·L)" substitution={`${n(gross.totalLoadKn,4)}/(${n(inputs.footingWidthM)}×${n(inputs.footingLengthM)})`} result={`${n(gross.averagePressureKpa,6)} kPa`}/><Equation name="Presión en cualquier punto" expression="q(x,y)=q̄+My(x−L/2)/Iy+Mx(y−B/2)/Ix" substitution="Iy=B·L³/12; Ix=L·B³/12" result="Plano lineal equilibrado"/><Equation name="Presión de esquina" expression="q(sx,sy)=q̄[1+sx·6ex/L+sy·6ey/B]" substitution="sx,sy = −1 o +1" result="Cuatro valores siguientes"/><Table rows={corners(gross.cornerPressuresKpa)}/><Table rows={[["Base comparada", inputs.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión máxima comparada', `${n(analysis.contact.maximumPressureForComparisonKpa)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa)} kPa`], ['Utilización', `${n(analysis.contact.utilization * 100,1)}% · ${analysis.contact.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada'}`]]}/></MemoSection>
    <MemoSection number="07" title="Presión última y cierre de equilibrio"><Equation name="Presión promedio última" expression="q̄u=Pu/(B·L)" substitution={`${n(inputs.factoredAxialLoadKn)}/${n(analysis.geometry.areaM2,6)}`} result={`${n(factored.averagePressureKpa,6)} kPa`}/><Equation name="Interacción última" expression="κu=6|exu|/L+6|eyu|/B" substitution={`${n(Math.abs(factored.normalizedEccentricityX),6)}+${n(Math.abs(factored.normalizedEccentricityY),6)}`} result={`${n(factored.kernInteraction,6)}`}/><Table rows={corners(factored.cornerPressuresKpa)}/><Table rows={[["∫q dA", `${n(analysis.equilibrium.integratedReactionKn,6)} kN · residual ${n(analysis.equilibrium.verticalResidualKn,9)}`], ['∫q(y−yc)dA', `${n(analysis.equilibrium.integratedMomentXKnM,6)} kN·m · residual ${n(analysis.equilibrium.momentXResidualKnM,9)}`], ['∫q(x−xc)dA', `${n(analysis.equilibrium.integratedMomentYKnM,6)} kN·m · residual ${n(analysis.equilibrium.momentYResidualKnM,9)}`]]}/></MemoSection>
    <MemoSection number="08" title="Demandas direccionales"><Equation name="Reacción integrada en X" expression="wx(x)=B·q̄x(x)=w0+kx" substitution={`w0=${n(analysis.directions.x.distributedReactionKnM.intercept)}; k=${n(analysis.directions.x.distributedReactionKnM.slope)}`} result={`V(L)=${n(analysis.directions.x.endShearKn,9)} kN; M(L)=${n(analysis.directions.x.endMomentKnM,9)} kN·m`}/><Equation name="Reacción integrada en Y" expression="wy(y)=L·q̄y(y)=w0+ky" substitution={`w0=${n(analysis.directions.y.distributedReactionKnM.intercept)}; k=${n(analysis.directions.y.distributedReactionKnM.slope)}`} result={`V(B)=${n(analysis.directions.y.endShearKn,9)} kN; M(B)=${n(analysis.directions.y.endMomentKnM,9)} kN·m`}/><Table rows={[["Cortante gobernante X", `${n(analysis.directions.x.governingShearDemandKn)} kN · η=${n(analysis.shearReference.x.utilization*100,1)}%`], ['Cortante gobernante Y', `${n(analysis.directions.y.governingShearDemandKn)} kN · η=${n(analysis.shearReference.y.utilization*100,1)}%`], ['Momento gobernante X', `${n(analysis.directions.x.governingFlexureDemandKnM)} kN·m`], ['Momento gobernante Y', `${n(analysis.directions.y.governingFlexureDemandKnM)} kN·m`]]}/><p className="memo-muted">Las franjas completas verifican equilibrio direccional; no sustituyen un modelo de placa cuando sea exigible.</p></MemoSection>
    <MemoSection number="09" title="Armado, desarrollo y punzonamiento"><Equation name="Acero mínimo" expression="As,min=0.0018×1000×h(mm)" substitution={`0.0018×1000×${n(inputs.footingThicknessM*1000,0)}`} result={`${n(analysis.minimumReinforcement.minimumAreaPerMeterCm2,2)} cm²/m`}/><Table rows={[["Acero X requerido", area(analysis.reinforcement.x.governingAreaPerMeterMm2)], ['Acero X colocado', area(analysis.reinforcement.x.providedAreaPerMeterMm2)], ['Acero Y requerido', area(analysis.reinforcement.y.governingAreaPerMeterMm2)], ['Acero Y colocado', area(analysis.reinforcement.y.providedAreaPerMeterMm2)], ['Desarrollo requerido', `${n(analysis.development.requiredDevelopmentLengthM)} m`], ['Punzonamiento', `No evaluado · ${analysis.punching.reason}`]]}/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value], index) => <div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: CornerFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: CornerFootingCalculationReport['profile']['traceability']; sources: CornerFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
