import type { MatFootingAnalysis } from '../../application/mat-footing-analysis'
import type { MatFootingInputs } from '../../domain/projects'
import type { MatFootingCalculationReport } from '../../reports/mat-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props = { analysis: MatFootingAnalysis | null; inputs: MatFootingInputs; report: MatFootingCalculationReport; cards: ResultCard[] }
const n = (value: number, decimals = 3) => value.toFixed(decimals)
const rowsForCorners = (values: { bottomLeft: number; bottomRight: number; topLeft: number; topRight: number }, unit: string): Array<[string, string]> => [
  ['Inferior izquierda', `${n(values.bottomLeft)} ${unit}`], ['Inferior derecha', `${n(values.bottomRight)} ${unit}`],
  ['Superior izquierda', `${n(values.topLeft)} ${unit}`], ['Superior derecha', `${n(values.topRight)} ${unit}`],
]

export function MatCalculationMemo({ analysis, inputs, report, cards }: Props) {
  if (!analysis) return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la losa de cimentación para generar la revisión de punta a punta.</p></section>
  const gross = analysis.contact.gross
  const factored = analysis.structural.factored
  const traceability = report.profile.traceability.filter((item) => item.appliesTo.includes('mat'))
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · LOSA DE CIMENTACIÓN</span><h2>{report.project.name}</h2><p>Memoria rígida–Winkler preliminar · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, alcance y fuentes"><Table rows={[["Perfil técnico", report.profile.label], ['Modelo', 'Losa rectangular rígida multicolumna'], ['Caso manual', 'AXC-MAT-001'], ['Derivación', 'AXC-MAT-DER-001'], ['Columnas', String(inputs.columns.length)], ['Diseño de placa', 'No evaluado']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos globales utilizados"><Table rows={report.inputs.map((item) => [item.label, `${item.value} ${item.unit}`])}/><h4 className="memo-subtitle">Columnas y cargas declaradas</h4><Table rows={inputs.columns.map((column) => [column.id, `Ps=${n(column.serviceLoadKn)} kN · Pu=${n(column.factoredLoadKn)} kN · (x,y)=(${n(column.centerXM)}, ${n(column.centerYM)}) m · ${n(column.lengthM)}×${n(column.widthM)} m`])}/></MemoSection>
    <MemoSection number="03" title="Geometría y pesos centrados"><Equation name="Área" expression="A=B·L" substitution={`${n(inputs.footingWidthM)}×${n(inputs.footingLengthM)}`} result={`${n(analysis.geometry.areaM2,6)} m²`}/><Equation name="Centroide" expression="(xc,yc)=(L/2,B/2)" substitution={`(${n(inputs.footingLengthM)}/2, ${n(inputs.footingWidthM)}/2)`} result={`(${n(analysis.geometry.centroidXM)}, ${n(analysis.geometry.centroidYM)}) m`}/><Equation name="Peso propio" expression="Wz=A·h·γc" substitution={`${n(analysis.geometry.areaM2)}×${n(inputs.footingThicknessM)}×${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.contact.footingSelfWeightKn)} kN`}/><Equation name="Relleno" expression="Wr=A·zr·γr" substitution={`${n(analysis.geometry.areaM2)}×${n(inputs.soilCoverDepthM)}×${n(inputs.soilUnitWeightKnM3)}`} result={`${n(analysis.contact.soilCoverWeightKn)} kN`}/></MemoSection>
    <MemoSection number="04" title="Resultante de servicio"><Equation name="Carga total" expression="P=ΣPs,i+Wz+Wr" substitution={`${n(analysis.loads.serviceColumnTotalKn)}+${n(analysis.contact.footingSelfWeightKn)}+${n(analysis.contact.soilCoverWeightKn)}`} result={`${n(gross.totalLoadKn)} kN`}/><Equation name="Momento respecto de Y" expression="My=ΣPs,i(xi−L/2)" substitution="Suma de todas las columnas" result={`${n(gross.momentYKnM)} kN·m`}/><Equation name="Momento respecto de X" expression="Mx=ΣPs,i(yi−B/2)" substitution="Suma de todas las columnas" result={`${n(gross.momentXKnM)} kN·m`}/><Equation name="Excentricidades" expression="ex=My/P; ey=Mx/P" substitution={`${n(gross.momentYKnM)}/${n(gross.totalLoadKn)}; ${n(gross.momentXKnM)}/${n(gross.totalLoadKn)}`} result={`ex=${n(gross.eccentricityXM,6)} m; ey=${n(gross.eccentricityYM,6)} m`}/></MemoSection>
    <MemoSection number="05" title="Núcleo central y plano de presiones"><Equation name="Interacción" expression="κ=6|ex|/L+6|ey|/B" substitution={`${n(Math.abs(gross.normalizedEccentricityX),6)}+${n(Math.abs(gross.normalizedEccentricityY),6)}`} result={`${n(gross.kernInteraction,6)} ≤ 1.000000`}/><Equation name="Presión promedio" expression="q̄=P/A" substitution={`${n(gross.totalLoadKn)}/${n(analysis.geometry.areaM2)}`} result={`${n(gross.averagePressureKpa,6)} kPa`}/><Equation name="Plano en cualquier punto" expression="q=P/A+My(x−L/2)/Iy+Mx(y−B/2)/Ix" substitution="Iy=B·L³/12; Ix=L·B³/12" result="Plano lineal en equilibrio"/><Equation name="Esquinas" expression="q=q̄[1+sx·6ex/L+sy·6ey/B]" substitution="sx,sy=−1 o +1" result="Valores siguientes"/><Table rows={rowsForCorners(gross.cornerPressuresKpa, 'kPa')}/></MemoSection>
    <MemoSection number="06" title="Capacidad admisible declarada"><Table rows={[["Base de comparación", inputs.bearingCapacityBasis === 'gross' ? 'Bruta' : 'Neta'], ['Presión máxima comparada', `${n(analysis.contact.maximumPressureForComparisonKpa)} kPa`], ['Capacidad admisible', `${n(inputs.allowableBearingKpa)} kPa`], ['Utilización', `${n(analysis.contact.utilization*100,1)}%`], ['Estado', analysis.contact.status === 'pass' ? 'Dentro de capacidad declarada' : 'Supera capacidad declarada']]}/></MemoSection>
    <MemoSection number="07" title="Pantalla de asentamiento rígida–Winkler">{analysis.settlement.status === 'calculated' ? <><Equation name="Relación local" expression="s(x,y)=qseleccionada(x,y)/k" substitution={`k=${n(analysis.settlement.subgradeModulusKnM3)} kN/m³ · base ${analysis.settlement.pressureBasis === 'gross' ? 'bruta' : 'neta'}`} result="Asentamientos de esquina"/><Table rows={rowsForCorners(analysis.settlement.cornerSettlementsMm, 'mm')}/><Table rows={[["Máximo", `${n(analysis.settlement.maximumSettlementMm)} mm · ${analysis.settlement.totalStatus}`], ['Mínimo', `${n(analysis.settlement.minimumSettlementMm)} mm`], ['Diferencial', `${n(analysis.settlement.differentialSettlementMm)} mm · ${analysis.settlement.differentialStatus}`]]}/><p className="memo-muted">k no es una propiedad universal del suelo: depende también de tamaño, forma, profundidad y rigidez. Esta pantalla no calcula consolidación ni deformación de placa.</p></> : <Table rows={[["Estado", 'No evaluado'], ['Motivo', analysis.settlement.reason]]}/>}</MemoSection>
    <MemoSection number="08" title="Carga última y auditoría de equilibrio"><Equation name="Carga última" expression="Pu=ΣPu,i" substitution={inputs.columns.map((column) => n(column.factoredLoadKn,0)).join(' + ')} result={`${n(factored.totalLoadKn)} kN`}/><Equation name="Interacción última" expression="κu=6|exu|/L+6|eyu|/B" substitution={`${n(Math.abs(factored.normalizedEccentricityX),6)}+${n(Math.abs(factored.normalizedEccentricityY),6)}`} result={n(factored.kernInteraction,6)}/><Table rows={rowsForCorners(factored.cornerPressuresKpa, 'kPa')}/><Table rows={[["∫q dA", `${n(analysis.equilibrium.integratedReactionKn,6)} kN · residual ${n(analysis.equilibrium.verticalResidualKn,9)}`], ['∫q(y−yc)dA', `${n(analysis.equilibrium.integratedMomentXKnM,6)} kN·m · residual ${n(analysis.equilibrium.momentXResidualKnM,9)}`], ['∫q(x−xc)dA', `${n(analysis.equilibrium.integratedMomentYKnM,6)} kN·m · residual ${n(analysis.equilibrium.momentYResidualKnM,9)}`]]}/></MemoSection>
    <MemoSection number="09" title="Proyecciones y límites estructurales"><Equation name="Proyección X" expression="wx(x)=B·q̄x(x)" substitution={`w0=${n(analysis.projections.x.distributedReactionKnM.intercept)}; pendiente=${n(analysis.projections.x.distributedReactionKnM.slope)}`} result={`V(L)=${n(analysis.projections.x.endShearKn,9)}; M(L)=${n(analysis.projections.x.endMomentKnM,9)}`}/><Equation name="Proyección Y" expression="wy(y)=L·q̄y(y)" substitution={`w0=${n(analysis.projections.y.distributedReactionKnM.intercept)}; pendiente=${n(analysis.projections.y.distributedReactionKnM.slope)}`} result={`V(B)=${n(analysis.projections.y.endShearKn,9)}; M(B)=${n(analysis.projections.y.endMomentKnM,9)}`}/><Table rows={[["Flexión/cortante de placa", `No evaluado · ${analysis.plate.reason}`], ['Punzonamiento', `No evaluado · ${analysis.punching.reason}`], ['Armado', `No evaluado · ${analysis.reinforcement.reason}`]]}/></MemoSection>
    <MemoSection number="10" title="Conclusión, trazabilidad y límites"><Table rows={cards.map((card) => [card.title, `${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit) => <li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section> }
function Table({ rows }: { rows: Array<[string, string]> }) { return <dl className="calculation-table">{rows.map(([term, value], index) => <div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl> }
function Equation({ name, expression, substitution, result }: { name: string; expression: string; substitution: string; result: string }) { return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div> }
function SourceList({ sources }: { sources: MatFootingCalculationReport['profile']['sources'] }) { return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source) => <article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section> }
function TraceabilityList({ items, sources }: { items: MatFootingCalculationReport['profile']['traceability']; sources: MatFootingCalculationReport['profile']['sources'] }) { return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item) => { const source = item.sourceId ? sources.find((candidate) => candidate.id === item.sourceId) : undefined; return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source ? <>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></> : null}</p><small>{item.applicability}</small></article> })}</section> }
