import type { TrapezoidalFootingAnalysis } from '../../application/trapezoidal-footing-analysis'
import { TrapezoidalFootingPlanSheet } from '../../components/TrapezoidalFootingTechnicalSheets'
import type { ProjectDocument, TrapezoidalFootingInputs } from '../../domain/projects'
import { trapezoidalCaseFieldDefinitions, trapezoidalCaseFieldGroups, type TrapezoidalCaseField, type TrapezoidalInputText } from './trapezoidal-case-fields'

type Props = { project: ProjectDocument; text: TrapezoidalInputText; openGroup: string; formatIssue: string | null; analysis: TrapezoidalFootingAnalysis | null; onOpenGroup: (id:string)=>void; onNameChange:(name:string)=>void; onFieldChange:(key:TrapezoidalCaseField,value:string)=>void; onBasisChange:(basis:TrapezoidalFootingInputs['bearingCapacityBasis'])=>void; onAnalyze:()=>void }

export function TrapezoidalCaseDefinition({ project, text, openGroup, formatIssue, analysis, onOpenGroup, onNameChange, onFieldChange, onBasisChange, onAnalyze }: Props) {
  return <section className="new-definition"><aside><div className="side-head"><span>01 · COMBINADA TRAPEZOIDAL</span><h1>Ancho variable</h1><p>Dos columnas alineadas sobre una base con lados inclinados.</p></div>{formatIssue && <p className="format-issue">{formatIssue}</p>}{trapezoidalCaseFieldGroups.map((group)=>{const opened=openGroup===group.id;const completed=group.keys.filter((key)=>Number(text[key].replace(',','.'))>0).length;return <section className="fold" key={group.id}><button className="fold-trigger" onClick={()=>onOpenGroup(opened?'':group.id)} aria-expanded={opened}><span><b>{group.label}</b><small>{opened?group.description:group.keys.length?`${completed}/${group.keys.length} valores declarados`:'Identificación y límites'}</small></span><i>{opened?'−':'+'}</i></button>{opened&&<div className="fold-body">{group.id==='project'&&<><label className="project-field">Nombre del proyecto<input value={project.name} onChange={(event)=>onNameChange(event.target.value)}/></label><p className="scope-note">Solo dos columnas interiores. Se bloquean contacto parcial, momentos transferidos, bordes y trapecios asimétricos.</p></>}{group.keys.map((key)=>{const field=trapezoidalCaseFieldDefinitions.find((item)=>item.key===key)!;return <label className="new-input" key={key}><span>{field.label}<small>{field.help}</small></span><div><input value={text[key]} inputMode="decimal" onChange={(event)=>onFieldChange(key,event.target.value)}/><em>{field.unit}</em></div></label>})}{group.id==='soil'&&<label className="basis-input"><span>Base de la capacidad declarada</span><select value={project.trapezoidalInputSnapshot.bearingCapacityBasis} onChange={(event)=>onBasisChange(event.target.value as TrapezoidalFootingInputs['bearingCapacityBasis'])}><option value="gross">Bruta</option><option value="net">Neta</option></select><small>Debe coincidir con el estudio geotécnico.</small></label>}</div>}</section>})}<button className="side-analyze" onClick={onAnalyze}>Analizar zapata trapezoidal</button></aside><section className="drawing-intro"><div><span>REPRESENTACIÓN PRELIMINAR</span><h1>Planta trapezoidal</h1><p>Los anchos extremos y las posiciones definen el centroide y la presión.</p></div><TrapezoidalFootingPlanSheet inputs={project.trapezoidalInputSnapshot} analysis={analysis}/></section></section>
}
