import type { TrapezoidalFootingAnalysis } from '../../application/trapezoidal-footing-analysis'
import type { TrapezoidalFootingInputs } from '../../domain/projects'
import type { TrapezoidalFootingCalculationReport } from '../../reports/trapezoidal-footing-calculation-report'
import { resultCardLabel, type ResultCard } from '../results/result-cards'

type Props={analysis:TrapezoidalFootingAnalysis|null;inputs:TrapezoidalFootingInputs;report:TrapezoidalFootingCalculationReport;cards:ResultCard[]}
const n=(value:number,decimals=3)=>value.toFixed(decimals)
const area=(value:number|null)=>value===null?'Sección insuficiente':`${n(value/100,2)} cm²/m`

export function TrapezoidalCalculationMemo({analysis,inputs,report,cards}:Props){
  if(!analysis)return <section className="memo-empty"><h2>Aún no hay cálculo para documentar</h2><p>Analiza la zapata trapezoidal para generar la memoria completa.</p></section>
  const traceability=report.profile.traceability.filter((item)=>item.appliesTo.includes('trapezoidal'))
  const punching=analysis.punching.reduce((best,item)=>item.utilization>best.utilization?item:best)
  const c=analysis.longitudinal.reactionPolynomialKnM
  return <article className="calculation-memo"><header className="calculation-memo-header"><span>ANDELOGIC ENGINEERING · ZAPATA TRAPEZOIDAL</span><h2>{report.project.name}</h2><p>Memoria para dos columnas y ancho variable · {new Date(report.generatedAt).toLocaleString('es-EC')}</p></header>
    <MemoSection number="01" title="Identificación, modelo y fuentes"><Table rows={[["Perfil técnico",report.profile.label],['Modelo','Zapata combinada trapezoidal rígida'],['Columnas','Dos interiores, alineadas sobre el eje longitudinal'],['Contacto','Presión longitudinal lineal y compresión en toda la base']]}/><SourceList sources={report.profile.sources}/></MemoSection>
    <MemoSection number="02" title="Datos utilizados"><Table rows={report.inputs.map((item)=>[item.label,`${item.value} ${item.unit}`])}/></MemoSection>
    <MemoSection number="03" title="Propiedades geométricas del trapecio"><Equation name="Pendiente del ancho" expression="kB = (B₂−B₁)/L" substitution={`(${n(inputs.rightFootingWidthM)}−${n(inputs.leftFootingWidthM)})/${n(inputs.footingLengthM)}`} result={n(analysis.geometry.widthSlope,5)}/><Equation name="Área" expression="A = L(B₁+B₂)/2" substitution={`${n(inputs.footingLengthM)}×(${n(inputs.leftFootingWidthM)}+${n(inputs.rightFootingWidthM)})/2`} result={`${n(analysis.geometry.areaM2)} m²`}/><Equation name="Primer momento de área" expression="Q = B₁L²/2 + kB·L³/3" substitution={`${n(inputs.leftFootingWidthM)}×${n(inputs.footingLengthM)}²/2 + ${n(analysis.geometry.widthSlope,5)}×${n(inputs.footingLengthM)}³/3`} result={`${n(analysis.geometry.firstAreaMomentM3)} m³`}/><Equation name="Centroide desde la izquierda" expression="x̄ = Q/A" substitution={`${n(analysis.geometry.firstAreaMomentM3)}/${n(analysis.geometry.areaM2)}`} result={`${n(analysis.geometry.centroidFromLeftM)} m`}/><Equation name="Segundo momento respecto al extremo" expression="J = B₁L³/3 + kB·L⁴/4" substitution="Integración de x²B(x) entre 0 y L" result={`${n(analysis.geometry.secondAreaMomentM4)} m⁴`}/><Equation name="Profundidad efectiva" expression="d = h−c−dᵦ/2" substitution={`${n(inputs.footingThicknessM)}−${n(inputs.concreteCoverM)}−${n(inputs.barDiameterM)}/2`} result={`${n(analysis.structural.effectiveDepthM)} m`}/></MemoSection>
    <MemoSection number="04" title="Equilibrio y contacto de servicio"><Equation name="Peso propio" expression="Wz = A·h·γc" substitution={`${n(analysis.geometry.areaM2)}×${n(inputs.footingThicknessM)}×${n(inputs.concreteUnitWeightKnM3)}`} result={`${n(analysis.contact.footingSelfWeightKn,2)} kN`}/><Equation name="Carga vertical total" expression="P = P₁+P₂+Wz+Wr" substitution={`${n(inputs.serviceColumn1LoadKn,1)}+${n(inputs.serviceColumn2LoadKn,1)}+${n(analysis.contact.footingSelfWeightKn,2)}+${n(analysis.contact.soilCoverWeightKn,2)}`} result={`${n(analysis.contact.gross.totalLoadKn,2)} kN`}/><Equation name="Momento desde el extremo" expression="M₀ = P₁x₁+P₂x₂+(Wz+Wr)x̄" substitution="Todas las acciones se expresan respecto de x=0" result={`${n(analysis.contact.gross.momentFromLeftKnM,2)} kN·m`}/><Equation name="Resultante" expression="xR = M₀/P; e=xR−x̄" substitution={`${n(analysis.contact.gross.momentFromLeftKnM,2)}/${n(analysis.contact.gross.totalLoadKn,2)}−${n(analysis.geometry.centroidFromLeftM)}`} result={`xR=${n(analysis.contact.gross.resultantFromLeftM)} m; e=${n(analysis.contact.gross.eccentricityFromCentroidM,5)} m`}/><Equation name="Sistema de presión" expression="aA+bQ=P; aQ+bJ=M₀" substitution={`a=${n(analysis.contact.gross.pressureInterceptKpa,4)}; b=${n(analysis.contact.gross.pressureSlopeKpaM,4)}`} result={`q₁=${n(analysis.contact.grossPressureLeftKpa,2)}; q₂=${n(analysis.contact.grossPressureRightKpa,2)} kPa`}/><Table rows={[["Base comparada",inputs.bearingCapacityBasis==='gross'?'Bruta':'Neta'],['Presión máxima comparada',`${n(analysis.contact.maximumPressureForComparisonKpa,2)} kPa`],['Capacidad admisible',`${n(inputs.allowableBearingKpa,2)} kPa`],['Utilización',`${n(analysis.contact.utilization*100,1)}% · ${analysis.contact.status==='pass'?'Dentro de capacidad declarada':'Supera capacidad declarada'}`],['Presión mínima bruta',`${n(analysis.contact.gross.minimumPressureKpa,2)} kPa · contacto completo`]]}/></MemoSection>
    <MemoSection number="05" title="Presión última y reacción longitudinal"><Equation name="Equilibrio último" expression="aᵤA+bᵤQ=Pᵤ; aᵤQ+bᵤJ=Mᵤ,0" substitution={`Pᵤ=${n(analysis.structural.factored.totalLoadKn,2)} kN; Mᵤ,0=${n(analysis.structural.factored.momentFromLeftKnM,2)} kN·m`} result={`qᵤ,1=${n(analysis.structural.factoredPressureLeftKpa,2)}; qᵤ,2=${n(analysis.structural.factoredPressureRightKpa,2)} kPa`}/><Equation name="Ancho local" expression="B(x)=B₁+kB·x" substitution={`B(x)=${n(inputs.leftFootingWidthM)}+${n(analysis.geometry.widthSlope,5)}x`} result={`B(0)=${n(inputs.leftFootingWidthM)} m; B(L)=${n(inputs.rightFootingWidthM)} m`}/><Equation name="Reacción ascendente" expression="w(x)=qᵤ(x)B(x)=c₀+c₁x+c₂x²" substitution={`c₀=${n(c.constant,4)}; c₁=${n(c.linear,4)}; c₂=${n(c.quadratic,5)}`} result="kN/m"/><Equation name="Cortante" expression="V(x)=c₀x+c₁x²/2+c₂x³/3−ΣPᵤ,i" substitution="Cada columna entra después de cruzar su centro." result={`V(L)=${n(analysis.longitudinal.endShearKn,7)} kN`}/><Equation name="Momento" expression="M(x)=c₀x²/2+c₁x³/6+c₂x⁴/12−ΣPᵤ,i(x−xᵢ)" substitution="Se evalúan extremos, columnas y raíces de V(x)." result={`M(L)=${n(analysis.longitudinal.endMomentKnM,7)} kN·m`}/><Table rows={[["Momento positivo máximo",`${n(analysis.longitudinal.maximumPositiveMomentKnM,2)} kN·m en x=${n(analysis.longitudinal.maximumPositiveMomentXM)} m`],['Momento negativo mínimo',`${n(analysis.longitudinal.minimumNegativeMomentKnM,2)} kN·m en x=${n(analysis.longitudinal.minimumNegativeMomentXM)} m`],['Momento absoluto gobernante',`${n(analysis.longitudinal.governingAbsoluteMomentKnM,2)} kN·m`]]}/></MemoSection>
    <MemoSection number="06" title="Cortante unidireccional"><Table rows={analysis.longitudinal.criticalShearSections.map((section)=>[`${section.label} · x=${n(section.xM)} m`,`B(x)=${n(section.localWidthM)} m; Vᵤ=${n(section.shearKn,2)} kN; φVᶜ=${n(section.reference.designShearStrengthKn,2)} kN; η=${n(section.reference.utilization*100,1)}%`])}/><Equation name="Demanda transversal por metro" expression="Vᵤ,t=qᵤ(xi)·máx(a−d,0)" substitution={`${n(analysis.transverse.shearLocalPressureKpa,2)}×${n(analysis.transverse.loadedLengthBeyondCriticalSectionM)}`} result={`${n(analysis.transverse.oneWayShearDemandKnPerM,2)} kN/m · columna ${analysis.transverse.governingShearColumn}`}/><Table rows={[["Referencia longitudinal gobernante",`${analysis.longitudinal.governingShearSection.label} · η ${n(analysis.longitudinal.governingShearSection.reference.utilization*100,1)}%`],['Referencia transversal',`${n(analysis.transverse.shearReference.designShearStrengthKn,2)} kN/m · η ${n(analysis.transverse.shearReference.utilization*100,1)}%`]]}/></MemoSection>
    <MemoSection number="07" title="Punzonamiento por columna"><Table rows={analysis.punching.flatMap((item)=>[[`Columna ${item.column} · ancho local`,`${n(item.localFootingWidthM)} m`],[`Columna ${item.column} · perímetro b₀`,`${n(item.criticalPerimeterM)} m`],[`Columna ${item.column} · reacción interior`,`${n(item.soilReactionInsideKn,2)} kN`],[`Columna ${item.column} · Vᵤ`,`${n(item.shearDemandKn,2)} kN`],[`Columna ${item.column} · φVᶜ y utilización`,`${n(item.designShearStrengthKn,2)} kN · ${n(item.utilization*100,1)}%`]] as Array<[string,string]>)}/><p className="memo-muted">Gobierna la columna {punching.column}. El motor exige que cada perímetro permanezca dentro de ambos bordes inclinados.</p></MemoSection>
    <MemoSection number="08" title="Flexión y armado"><Equation name="Flexión transversal por metro" expression="Mᵤ,t=qᵤ(xi)·a²/2" substitution={`${n(analysis.transverse.flexureLocalPressureKpa,2)}×${n(analysis.transverse.cantileverProjectionM)}²/2`} result={`${n(analysis.transverse.flexureDemandKnMPerM,2)} kN·m/m · columna ${analysis.transverse.governingFlexureColumn}`}/><Equation name="Acero mínimo" expression="Aₛ,min=0.0018×1000×h(mm)" substitution={`0.0018×1000×${n(inputs.footingThicknessM*1000,0)}`} result={`${n(analysis.minimumReinforcement.minimumAreaPerMeterCm2,2)} cm²/m`}/><Table rows={[["Longitudinal inferior requerido",area(analysis.reinforcement.longitudinalBottom.governingAreaPerMeterMm2)],['Longitudinal inferior colocado',area(analysis.reinforcement.longitudinalBottom.providedAreaPerMeterMm2)],['Longitudinal superior requerido',area(analysis.reinforcement.longitudinalTop.governingAreaPerMeterMm2)],['Longitudinal superior colocado',area(analysis.reinforcement.longitudinalTop.providedAreaPerMeterMm2)],['Transversal requerido',area(analysis.reinforcement.transverse.governingAreaPerMeterMm2)],['Transversal colocado',area(analysis.reinforcement.transverse.providedAreaPerMeterMm2)]]}/></MemoSection>
    <MemoSection number="09" title="Desarrollo y exclusiones"><Equation name="Longitud requerida" expression="lᵈ=fy/(1.4√f′c)·dᵦ" substitution={`${n(inputs.steelYieldStrengthMpa,2)}/(1.4√${n(inputs.concreteStrengthMpa,2)})×${n(inputs.barDiameterM)}`} result={`${n(analysis.development.requiredDevelopmentLengthM)} m`}/><Table rows={[["Disponible longitudinal",`${n(inputs.longitudinalDevelopmentAvailableM)} m · ${analysis.development.lengthDirection.status==='meets-guide-reference'?'Dentro de referencia':'Requiere ajuste'}`],['Disponible transversal',`${n(inputs.transverseDevelopmentAvailableM)} m · ${analysis.development.widthDirection.status==='meets-guide-reference'?'Dentro de referencia':'Requiere ajuste'}`],['Contacto parcial o levantamiento','Fuera de alcance; el motor bloquea el caso'],['Bordes, momentos y fuerzas horizontales','Fuera de alcance'],['Asentamientos','Revisión externa del estudio geotécnico']]}/></MemoSection>
    <MemoSection number="10" title="Conclusión y trazabilidad"><Table rows={cards.map((card)=>[card.title,`${resultCardLabel(card.state)} · ${card.value}`])}/><TraceabilityList items={traceability} sources={report.profile.sources}/><ul className="memo-limits">{report.limitations.map((limit)=><li key={limit}>{limit}</li>)}</ul></MemoSection>
  </article>
}

function MemoSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="calculation-section"><header><span>{number}</span><h3>{title}</h3></header>{children}</section>}
function Table({rows}:{rows:Array<[string,string]>}){return <dl className="calculation-table">{rows.map(([term,value],index)=><div key={`${term}-${index}`}><dt>{term}</dt><dd>{value}</dd></div>)}</dl>}
function Equation({name,expression,substitution,result}:{name:string;expression:string;substitution:string;result:string}){return <div className="calculation-equation"><strong>{name}</strong><code>{expression}</code><p>{substitution}</p><b>= {result}</b></div>}
function SourceList({sources}:{sources:TrapezoidalFootingCalculationReport['profile']['sources']}){return <section className="memo-sources"><h4>Fuentes públicas del perfil</h4>{sources.map((source)=><article key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><b>{source.version}</b><p>{source.scope}</p></article>)}</section>}
function TraceabilityList({items,sources}:{items:TrapezoidalFootingCalculationReport['profile']['traceability'];sources:TrapezoidalFootingCalculationReport['profile']['sources']}){return <section className="memo-traceability"><h4>Aplicabilidad por módulo</h4>{items.map((item)=>{const source=item.sourceId?sources.find((candidate)=>candidate.id===item.sourceId):undefined;return <article key={item.id}><strong>{item.module}</strong><span>{item.basis}</span><p>{item.reference}{source?<>&nbsp;<a href={source.url} target="_blank" rel="noreferrer">Abrir fuente ↗</a></>:null}</p><small>{item.applicability}</small></article>})}</section>}
